/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the LegalDocument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LegalDocument{}

// LegalDocument struct for LegalDocument
type LegalDocument struct {
	DocumentType string `json:"document_type"`
	Version string `json:"version"`
	Title string `json:"title"`
	EffectiveFrom time.Time `json:"effective_from"`
	SummaryText *string `json:"summary_text,omitempty"`
	FullTextUrl *string `json:"full_text_url,omitempty"`
	IsCurrent *bool `json:"is_current,omitempty"`
	ChangeSummary *string `json:"change_summary,omitempty"`
	RequiresReacceptance *bool `json:"requires_reacceptance,omitempty"`
	// Full document body (Markdown). F3.LEGAL.01: seeded with a PLACEHOLDER pending lawyer review — see src/bootstrap.ts ensureLegalDocumentPlaceholders().
	Body *string `json:"body,omitempty"`
	// F3.LEGAL.01: document language (cs/en). NOT the Strapi i18n plugin locale field (i18n is not enabled on this CT) — a plain string so cs/en variants of the same document_type+version can coexist as separate rows.
	LocaleCode *string `json:"locale_code,omitempty"`
}

type _LegalDocument LegalDocument

// NewLegalDocument instantiates a new LegalDocument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLegalDocument(documentType string, version string, title string, effectiveFrom time.Time) *LegalDocument {
	this := LegalDocument{}
	this.DocumentType = documentType
	this.Version = version
	this.Title = title
	this.EffectiveFrom = effectiveFrom
	return &this
}

// NewLegalDocumentWithDefaults instantiates a new LegalDocument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLegalDocumentWithDefaults() *LegalDocument {
	this := LegalDocument{}
	return &this
}

// GetDocumentType returns the DocumentType field value
func (o *LegalDocument) GetDocumentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentType
}

// GetDocumentTypeOk returns a tuple with the DocumentType field value
// and a boolean to check if the value has been set.
func (o *LegalDocument) GetDocumentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentType, true
}

// SetDocumentType sets field value
func (o *LegalDocument) SetDocumentType(v string) {
	o.DocumentType = v
}

// GetVersion returns the Version field value
func (o *LegalDocument) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *LegalDocument) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *LegalDocument) SetVersion(v string) {
	o.Version = v
}

// GetTitle returns the Title field value
func (o *LegalDocument) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *LegalDocument) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *LegalDocument) SetTitle(v string) {
	o.Title = v
}

// GetEffectiveFrom returns the EffectiveFrom field value
func (o *LegalDocument) GetEffectiveFrom() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EffectiveFrom
}

// GetEffectiveFromOk returns a tuple with the EffectiveFrom field value
// and a boolean to check if the value has been set.
func (o *LegalDocument) GetEffectiveFromOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EffectiveFrom, true
}

// SetEffectiveFrom sets field value
func (o *LegalDocument) SetEffectiveFrom(v time.Time) {
	o.EffectiveFrom = v
}

// GetSummaryText returns the SummaryText field value if set, zero value otherwise.
func (o *LegalDocument) GetSummaryText() string {
	if o == nil || IsNil(o.SummaryText) {
		var ret string
		return ret
	}
	return *o.SummaryText
}

// GetSummaryTextOk returns a tuple with the SummaryText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LegalDocument) GetSummaryTextOk() (*string, bool) {
	if o == nil || IsNil(o.SummaryText) {
		return nil, false
	}
	return o.SummaryText, true
}

// HasSummaryText returns a boolean if a field has been set.
func (o *LegalDocument) HasSummaryText() bool {
	if o != nil && !IsNil(o.SummaryText) {
		return true
	}

	return false
}

// SetSummaryText gets a reference to the given string and assigns it to the SummaryText field.
func (o *LegalDocument) SetSummaryText(v string) {
	o.SummaryText = &v
}

// GetFullTextUrl returns the FullTextUrl field value if set, zero value otherwise.
func (o *LegalDocument) GetFullTextUrl() string {
	if o == nil || IsNil(o.FullTextUrl) {
		var ret string
		return ret
	}
	return *o.FullTextUrl
}

// GetFullTextUrlOk returns a tuple with the FullTextUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LegalDocument) GetFullTextUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FullTextUrl) {
		return nil, false
	}
	return o.FullTextUrl, true
}

// HasFullTextUrl returns a boolean if a field has been set.
func (o *LegalDocument) HasFullTextUrl() bool {
	if o != nil && !IsNil(o.FullTextUrl) {
		return true
	}

	return false
}

// SetFullTextUrl gets a reference to the given string and assigns it to the FullTextUrl field.
func (o *LegalDocument) SetFullTextUrl(v string) {
	o.FullTextUrl = &v
}

// GetIsCurrent returns the IsCurrent field value if set, zero value otherwise.
func (o *LegalDocument) GetIsCurrent() bool {
	if o == nil || IsNil(o.IsCurrent) {
		var ret bool
		return ret
	}
	return *o.IsCurrent
}

// GetIsCurrentOk returns a tuple with the IsCurrent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LegalDocument) GetIsCurrentOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCurrent) {
		return nil, false
	}
	return o.IsCurrent, true
}

// HasIsCurrent returns a boolean if a field has been set.
func (o *LegalDocument) HasIsCurrent() bool {
	if o != nil && !IsNil(o.IsCurrent) {
		return true
	}

	return false
}

// SetIsCurrent gets a reference to the given bool and assigns it to the IsCurrent field.
func (o *LegalDocument) SetIsCurrent(v bool) {
	o.IsCurrent = &v
}

// GetChangeSummary returns the ChangeSummary field value if set, zero value otherwise.
func (o *LegalDocument) GetChangeSummary() string {
	if o == nil || IsNil(o.ChangeSummary) {
		var ret string
		return ret
	}
	return *o.ChangeSummary
}

// GetChangeSummaryOk returns a tuple with the ChangeSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LegalDocument) GetChangeSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.ChangeSummary) {
		return nil, false
	}
	return o.ChangeSummary, true
}

// HasChangeSummary returns a boolean if a field has been set.
func (o *LegalDocument) HasChangeSummary() bool {
	if o != nil && !IsNil(o.ChangeSummary) {
		return true
	}

	return false
}

// SetChangeSummary gets a reference to the given string and assigns it to the ChangeSummary field.
func (o *LegalDocument) SetChangeSummary(v string) {
	o.ChangeSummary = &v
}

// GetRequiresReacceptance returns the RequiresReacceptance field value if set, zero value otherwise.
func (o *LegalDocument) GetRequiresReacceptance() bool {
	if o == nil || IsNil(o.RequiresReacceptance) {
		var ret bool
		return ret
	}
	return *o.RequiresReacceptance
}

// GetRequiresReacceptanceOk returns a tuple with the RequiresReacceptance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LegalDocument) GetRequiresReacceptanceOk() (*bool, bool) {
	if o == nil || IsNil(o.RequiresReacceptance) {
		return nil, false
	}
	return o.RequiresReacceptance, true
}

// HasRequiresReacceptance returns a boolean if a field has been set.
func (o *LegalDocument) HasRequiresReacceptance() bool {
	if o != nil && !IsNil(o.RequiresReacceptance) {
		return true
	}

	return false
}

// SetRequiresReacceptance gets a reference to the given bool and assigns it to the RequiresReacceptance field.
func (o *LegalDocument) SetRequiresReacceptance(v bool) {
	o.RequiresReacceptance = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *LegalDocument) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LegalDocument) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *LegalDocument) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *LegalDocument) SetBody(v string) {
	o.Body = &v
}

// GetLocaleCode returns the LocaleCode field value if set, zero value otherwise.
func (o *LegalDocument) GetLocaleCode() string {
	if o == nil || IsNil(o.LocaleCode) {
		var ret string
		return ret
	}
	return *o.LocaleCode
}

// GetLocaleCodeOk returns a tuple with the LocaleCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LegalDocument) GetLocaleCodeOk() (*string, bool) {
	if o == nil || IsNil(o.LocaleCode) {
		return nil, false
	}
	return o.LocaleCode, true
}

// HasLocaleCode returns a boolean if a field has been set.
func (o *LegalDocument) HasLocaleCode() bool {
	if o != nil && !IsNil(o.LocaleCode) {
		return true
	}

	return false
}

// SetLocaleCode gets a reference to the given string and assigns it to the LocaleCode field.
func (o *LegalDocument) SetLocaleCode(v string) {
	o.LocaleCode = &v
}

func (o LegalDocument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LegalDocument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["document_type"] = o.DocumentType
	toSerialize["version"] = o.Version
	toSerialize["title"] = o.Title
	toSerialize["effective_from"] = o.EffectiveFrom
	if !IsNil(o.SummaryText) {
		toSerialize["summary_text"] = o.SummaryText
	}
	if !IsNil(o.FullTextUrl) {
		toSerialize["full_text_url"] = o.FullTextUrl
	}
	if !IsNil(o.IsCurrent) {
		toSerialize["is_current"] = o.IsCurrent
	}
	if !IsNil(o.ChangeSummary) {
		toSerialize["change_summary"] = o.ChangeSummary
	}
	if !IsNil(o.RequiresReacceptance) {
		toSerialize["requires_reacceptance"] = o.RequiresReacceptance
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.LocaleCode) {
		toSerialize["locale_code"] = o.LocaleCode
	}
	return toSerialize, nil
}

func (o *LegalDocument) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"document_type",
		"version",
		"title",
		"effective_from",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLegalDocument := _LegalDocument{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLegalDocument)

	if err != nil {
		return err
	}

	*o = LegalDocument(varLegalDocument)

	return err
}

type NullableLegalDocument struct {
	value *LegalDocument
	isSet bool
}

func (v NullableLegalDocument) Get() *LegalDocument {
	return v.value
}

func (v *NullableLegalDocument) Set(val *LegalDocument) {
	v.value = val
	v.isSet = true
}

func (v NullableLegalDocument) IsSet() bool {
	return v.isSet
}

func (v *NullableLegalDocument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLegalDocument(val *LegalDocument) *NullableLegalDocument {
	return &NullableLegalDocument{value: val, isSet: true}
}

func (v NullableLegalDocument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLegalDocument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


