/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FindCloudVpnGateway200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindCloudVpnGateway200ResponseDataInner{}

// FindCloudVpnGateway200ResponseDataInner struct for FindCloudVpnGateway200ResponseDataInner
type FindCloudVpnGateway200ResponseDataInner struct {
	Name string `json:"name"`
	Type *string `json:"type,omitempty"`
	State *string `json:"state,omitempty"`
	ExternalId *string `json:"external_id,omitempty"`
	// Arbitrary JSON value (object, array, string, number, boolean, or null)
	Metadata interface{} `json:"metadata,omitempty"`
	Network *CreateAccessReviewRequestDataReviewer `json:"network,omitempty"`
	Organisation *CreateAccessReviewRequestDataReviewer `json:"organisation,omitempty"`
	DocumentId *string `json:"documentId,omitempty"`
	Id *int32 `json:"id,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	PublishedAt NullableTime `json:"publishedAt,omitempty"`
}

type _FindCloudVpnGateway200ResponseDataInner FindCloudVpnGateway200ResponseDataInner

// NewFindCloudVpnGateway200ResponseDataInner instantiates a new FindCloudVpnGateway200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindCloudVpnGateway200ResponseDataInner(name string) *FindCloudVpnGateway200ResponseDataInner {
	this := FindCloudVpnGateway200ResponseDataInner{}
	this.Name = name
	return &this
}

// NewFindCloudVpnGateway200ResponseDataInnerWithDefaults instantiates a new FindCloudVpnGateway200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindCloudVpnGateway200ResponseDataInnerWithDefaults() *FindCloudVpnGateway200ResponseDataInner {
	this := FindCloudVpnGateway200ResponseDataInner{}
	return &this
}

// GetName returns the Name field value
func (o *FindCloudVpnGateway200ResponseDataInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FindCloudVpnGateway200ResponseDataInner) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *FindCloudVpnGateway200ResponseDataInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *FindCloudVpnGateway200ResponseDataInner) SetType(v string) {
	o.Type = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *FindCloudVpnGateway200ResponseDataInner) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *FindCloudVpnGateway200ResponseDataInner) SetState(v string) {
	o.State = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *FindCloudVpnGateway200ResponseDataInner) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *FindCloudVpnGateway200ResponseDataInner) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FindCloudVpnGateway200ResponseDataInner) GetMetadata() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FindCloudVpnGateway200ResponseDataInner) GetMetadataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return &o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given interface{} and assigns it to the Metadata field.
func (o *FindCloudVpnGateway200ResponseDataInner) SetMetadata(v interface{}) {
	o.Metadata = v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *FindCloudVpnGateway200ResponseDataInner) GetNetwork() CreateAccessReviewRequestDataReviewer {
	if o == nil || IsNil(o.Network) {
		var ret CreateAccessReviewRequestDataReviewer
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) GetNetworkOk() (*CreateAccessReviewRequestDataReviewer, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given CreateAccessReviewRequestDataReviewer and assigns it to the Network field.
func (o *FindCloudVpnGateway200ResponseDataInner) SetNetwork(v CreateAccessReviewRequestDataReviewer) {
	o.Network = &v
}

// GetOrganisation returns the Organisation field value if set, zero value otherwise.
func (o *FindCloudVpnGateway200ResponseDataInner) GetOrganisation() CreateAccessReviewRequestDataReviewer {
	if o == nil || IsNil(o.Organisation) {
		var ret CreateAccessReviewRequestDataReviewer
		return ret
	}
	return *o.Organisation
}

// GetOrganisationOk returns a tuple with the Organisation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) GetOrganisationOk() (*CreateAccessReviewRequestDataReviewer, bool) {
	if o == nil || IsNil(o.Organisation) {
		return nil, false
	}
	return o.Organisation, true
}

// HasOrganisation returns a boolean if a field has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) HasOrganisation() bool {
	if o != nil && !IsNil(o.Organisation) {
		return true
	}

	return false
}

// SetOrganisation gets a reference to the given CreateAccessReviewRequestDataReviewer and assigns it to the Organisation field.
func (o *FindCloudVpnGateway200ResponseDataInner) SetOrganisation(v CreateAccessReviewRequestDataReviewer) {
	o.Organisation = &v
}

// GetDocumentId returns the DocumentId field value if set, zero value otherwise.
func (o *FindCloudVpnGateway200ResponseDataInner) GetDocumentId() string {
	if o == nil || IsNil(o.DocumentId) {
		var ret string
		return ret
	}
	return *o.DocumentId
}

// GetDocumentIdOk returns a tuple with the DocumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) GetDocumentIdOk() (*string, bool) {
	if o == nil || IsNil(o.DocumentId) {
		return nil, false
	}
	return o.DocumentId, true
}

// HasDocumentId returns a boolean if a field has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) HasDocumentId() bool {
	if o != nil && !IsNil(o.DocumentId) {
		return true
	}

	return false
}

// SetDocumentId gets a reference to the given string and assigns it to the DocumentId field.
func (o *FindCloudVpnGateway200ResponseDataInner) SetDocumentId(v string) {
	o.DocumentId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FindCloudVpnGateway200ResponseDataInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *FindCloudVpnGateway200ResponseDataInner) SetId(v int32) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *FindCloudVpnGateway200ResponseDataInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *FindCloudVpnGateway200ResponseDataInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *FindCloudVpnGateway200ResponseDataInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *FindCloudVpnGateway200ResponseDataInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetPublishedAt returns the PublishedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FindCloudVpnGateway200ResponseDataInner) GetPublishedAt() time.Time {
	if o == nil || IsNil(o.PublishedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.PublishedAt.Get()
}

// GetPublishedAtOk returns a tuple with the PublishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FindCloudVpnGateway200ResponseDataInner) GetPublishedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PublishedAt.Get(), o.PublishedAt.IsSet()
}

// HasPublishedAt returns a boolean if a field has been set.
func (o *FindCloudVpnGateway200ResponseDataInner) HasPublishedAt() bool {
	if o != nil && o.PublishedAt.IsSet() {
		return true
	}

	return false
}

// SetPublishedAt gets a reference to the given NullableTime and assigns it to the PublishedAt field.
func (o *FindCloudVpnGateway200ResponseDataInner) SetPublishedAt(v time.Time) {
	o.PublishedAt.Set(&v)
}
// SetPublishedAtNil sets the value for PublishedAt to be an explicit nil
func (o *FindCloudVpnGateway200ResponseDataInner) SetPublishedAtNil() {
	o.PublishedAt.Set(nil)
}

// UnsetPublishedAt ensures that no value is present for PublishedAt, not even an explicit nil
func (o *FindCloudVpnGateway200ResponseDataInner) UnsetPublishedAt() {
	o.PublishedAt.Unset()
}

func (o FindCloudVpnGateway200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindCloudVpnGateway200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.ExternalId) {
		toSerialize["external_id"] = o.ExternalId
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.Organisation) {
		toSerialize["organisation"] = o.Organisation
	}
	if !IsNil(o.DocumentId) {
		toSerialize["documentId"] = o.DocumentId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.PublishedAt.IsSet() {
		toSerialize["publishedAt"] = o.PublishedAt.Get()
	}
	return toSerialize, nil
}

func (o *FindCloudVpnGateway200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFindCloudVpnGateway200ResponseDataInner := _FindCloudVpnGateway200ResponseDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFindCloudVpnGateway200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = FindCloudVpnGateway200ResponseDataInner(varFindCloudVpnGateway200ResponseDataInner)

	return err
}

type NullableFindCloudVpnGateway200ResponseDataInner struct {
	value *FindCloudVpnGateway200ResponseDataInner
	isSet bool
}

func (v NullableFindCloudVpnGateway200ResponseDataInner) Get() *FindCloudVpnGateway200ResponseDataInner {
	return v.value
}

func (v *NullableFindCloudVpnGateway200ResponseDataInner) Set(val *FindCloudVpnGateway200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFindCloudVpnGateway200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFindCloudVpnGateway200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindCloudVpnGateway200ResponseDataInner(val *FindCloudVpnGateway200ResponseDataInner) *NullableFindCloudVpnGateway200ResponseDataInner {
	return &NullableFindCloudVpnGateway200ResponseDataInner{value: val, isSet: true}
}

func (v NullableFindCloudVpnGateway200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindCloudVpnGateway200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


