/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the CreateAgentPolicy200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAgentPolicy200Response{}

// CreateAgentPolicy200Response struct for CreateAgentPolicy200Response
type CreateAgentPolicy200Response struct {
	Data *FindAgentPolicy200ResponseDataInner `json:"data,omitempty"`
}

// NewCreateAgentPolicy200Response instantiates a new CreateAgentPolicy200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAgentPolicy200Response() *CreateAgentPolicy200Response {
	this := CreateAgentPolicy200Response{}
	return &this
}

// NewCreateAgentPolicy200ResponseWithDefaults instantiates a new CreateAgentPolicy200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAgentPolicy200ResponseWithDefaults() *CreateAgentPolicy200Response {
	this := CreateAgentPolicy200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateAgentPolicy200Response) GetData() FindAgentPolicy200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret FindAgentPolicy200ResponseDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentPolicy200Response) GetDataOk() (*FindAgentPolicy200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateAgentPolicy200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given FindAgentPolicy200ResponseDataInner and assigns it to the Data field.
func (o *CreateAgentPolicy200Response) SetData(v FindAgentPolicy200ResponseDataInner) {
	o.Data = &v
}

func (o CreateAgentPolicy200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAgentPolicy200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateAgentPolicy200Response struct {
	value *CreateAgentPolicy200Response
	isSet bool
}

func (v NullableCreateAgentPolicy200Response) Get() *CreateAgentPolicy200Response {
	return v.value
}

func (v *NullableCreateAgentPolicy200Response) Set(val *CreateAgentPolicy200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAgentPolicy200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAgentPolicy200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAgentPolicy200Response(val *CreateAgentPolicy200Response) *NullableCreateAgentPolicy200Response {
	return &NullableCreateAgentPolicy200Response{value: val, isSet: true}
}

func (v NullableCreateAgentPolicy200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAgentPolicy200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


