/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the CreateAuditArtifact200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAuditArtifact200Response{}

// CreateAuditArtifact200Response struct for CreateAuditArtifact200Response
type CreateAuditArtifact200Response struct {
	Data *FindAuditArtifact200ResponseDataInner `json:"data,omitempty"`
}

// NewCreateAuditArtifact200Response instantiates a new CreateAuditArtifact200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAuditArtifact200Response() *CreateAuditArtifact200Response {
	this := CreateAuditArtifact200Response{}
	return &this
}

// NewCreateAuditArtifact200ResponseWithDefaults instantiates a new CreateAuditArtifact200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAuditArtifact200ResponseWithDefaults() *CreateAuditArtifact200Response {
	this := CreateAuditArtifact200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateAuditArtifact200Response) GetData() FindAuditArtifact200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret FindAuditArtifact200ResponseDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAuditArtifact200Response) GetDataOk() (*FindAuditArtifact200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateAuditArtifact200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given FindAuditArtifact200ResponseDataInner and assigns it to the Data field.
func (o *CreateAuditArtifact200Response) SetData(v FindAuditArtifact200ResponseDataInner) {
	o.Data = &v
}

func (o CreateAuditArtifact200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAuditArtifact200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateAuditArtifact200Response struct {
	value *CreateAuditArtifact200Response
	isSet bool
}

func (v NullableCreateAuditArtifact200Response) Get() *CreateAuditArtifact200Response {
	return v.value
}

func (v *NullableCreateAuditArtifact200Response) Set(val *CreateAuditArtifact200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAuditArtifact200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAuditArtifact200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAuditArtifact200Response(val *CreateAuditArtifact200Response) *NullableCreateAuditArtifact200Response {
	return &NullableCreateAuditArtifact200Response{value: val, isSet: true}
}

func (v NullableCreateAuditArtifact200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAuditArtifact200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


