/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the CreateCloudCredential200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCloudCredential200Response{}

// CreateCloudCredential200Response struct for CreateCloudCredential200Response
type CreateCloudCredential200Response struct {
	Data *FindCloudCredential200ResponseDataInner `json:"data,omitempty"`
}

// NewCreateCloudCredential200Response instantiates a new CreateCloudCredential200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCloudCredential200Response() *CreateCloudCredential200Response {
	this := CreateCloudCredential200Response{}
	return &this
}

// NewCreateCloudCredential200ResponseWithDefaults instantiates a new CreateCloudCredential200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCloudCredential200ResponseWithDefaults() *CreateCloudCredential200Response {
	this := CreateCloudCredential200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateCloudCredential200Response) GetData() FindCloudCredential200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret FindCloudCredential200ResponseDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCloudCredential200Response) GetDataOk() (*FindCloudCredential200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateCloudCredential200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given FindCloudCredential200ResponseDataInner and assigns it to the Data field.
func (o *CreateCloudCredential200Response) SetData(v FindCloudCredential200ResponseDataInner) {
	o.Data = &v
}

func (o CreateCloudCredential200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCloudCredential200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateCloudCredential200Response struct {
	value *CreateCloudCredential200Response
	isSet bool
}

func (v NullableCreateCloudCredential200Response) Get() *CreateCloudCredential200Response {
	return v.value
}

func (v *NullableCreateCloudCredential200Response) Set(val *CreateCloudCredential200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCloudCredential200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCloudCredential200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCloudCredential200Response(val *CreateCloudCredential200Response) *NullableCreateCloudCredential200Response {
	return &NullableCreateCloudCredential200Response{value: val, isSet: true}
}

func (v NullableCreateCloudCredential200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCloudCredential200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


