/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the FindForumUserCredential200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindForumUserCredential200Response{}

// FindForumUserCredential200Response struct for FindForumUserCredential200Response
type FindForumUserCredential200Response struct {
	Data []FindForumUserCredential200ResponseDataInner `json:"data,omitempty"`
	Meta *FindAccessReviewItem200ResponseMeta `json:"meta,omitempty"`
}

// NewFindForumUserCredential200Response instantiates a new FindForumUserCredential200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindForumUserCredential200Response() *FindForumUserCredential200Response {
	this := FindForumUserCredential200Response{}
	return &this
}

// NewFindForumUserCredential200ResponseWithDefaults instantiates a new FindForumUserCredential200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindForumUserCredential200ResponseWithDefaults() *FindForumUserCredential200Response {
	this := FindForumUserCredential200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FindForumUserCredential200Response) GetData() []FindForumUserCredential200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []FindForumUserCredential200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindForumUserCredential200Response) GetDataOk() ([]FindForumUserCredential200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FindForumUserCredential200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []FindForumUserCredential200ResponseDataInner and assigns it to the Data field.
func (o *FindForumUserCredential200Response) SetData(v []FindForumUserCredential200ResponseDataInner) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *FindForumUserCredential200Response) GetMeta() FindAccessReviewItem200ResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret FindAccessReviewItem200ResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindForumUserCredential200Response) GetMetaOk() (*FindAccessReviewItem200ResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *FindForumUserCredential200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given FindAccessReviewItem200ResponseMeta and assigns it to the Meta field.
func (o *FindForumUserCredential200Response) SetMeta(v FindAccessReviewItem200ResponseMeta) {
	o.Meta = &v
}

func (o FindForumUserCredential200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindForumUserCredential200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableFindForumUserCredential200Response struct {
	value *FindForumUserCredential200Response
	isSet bool
}

func (v NullableFindForumUserCredential200Response) Get() *FindForumUserCredential200Response {
	return v.value
}

func (v *NullableFindForumUserCredential200Response) Set(val *FindForumUserCredential200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFindForumUserCredential200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFindForumUserCredential200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindForumUserCredential200Response(val *FindForumUserCredential200Response) *NullableFindForumUserCredential200Response {
	return &NullableFindForumUserCredential200Response{value: val, isSet: true}
}

func (v NullableFindForumUserCredential200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindForumUserCredential200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


