/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the CreateDeployment200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDeployment200Response{}

// CreateDeployment200Response struct for CreateDeployment200Response
type CreateDeployment200Response struct {
	Data *FindDeployment200ResponseDataInner `json:"data,omitempty"`
}

// NewCreateDeployment200Response instantiates a new CreateDeployment200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDeployment200Response() *CreateDeployment200Response {
	this := CreateDeployment200Response{}
	return &this
}

// NewCreateDeployment200ResponseWithDefaults instantiates a new CreateDeployment200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDeployment200ResponseWithDefaults() *CreateDeployment200Response {
	this := CreateDeployment200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateDeployment200Response) GetData() FindDeployment200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret FindDeployment200ResponseDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDeployment200Response) GetDataOk() (*FindDeployment200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateDeployment200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given FindDeployment200ResponseDataInner and assigns it to the Data field.
func (o *CreateDeployment200Response) SetData(v FindDeployment200ResponseDataInner) {
	o.Data = &v
}

func (o CreateDeployment200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDeployment200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateDeployment200Response struct {
	value *CreateDeployment200Response
	isSet bool
}

func (v NullableCreateDeployment200Response) Get() *CreateDeployment200Response {
	return v.value
}

func (v *NullableCreateDeployment200Response) Set(val *CreateDeployment200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDeployment200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDeployment200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDeployment200Response(val *CreateDeployment200Response) *NullableCreateDeployment200Response {
	return &NullableCreateDeployment200Response{value: val, isSet: true}
}

func (v NullableCreateDeployment200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDeployment200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


