/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the FindOneBillingSyncLog200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindOneBillingSyncLog200Response{}

// FindOneBillingSyncLog200Response struct for FindOneBillingSyncLog200Response
type FindOneBillingSyncLog200Response struct {
	Data *FindBillingSyncLog200ResponseDataInner `json:"data,omitempty"`
}

// NewFindOneBillingSyncLog200Response instantiates a new FindOneBillingSyncLog200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindOneBillingSyncLog200Response() *FindOneBillingSyncLog200Response {
	this := FindOneBillingSyncLog200Response{}
	return &this
}

// NewFindOneBillingSyncLog200ResponseWithDefaults instantiates a new FindOneBillingSyncLog200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindOneBillingSyncLog200ResponseWithDefaults() *FindOneBillingSyncLog200Response {
	this := FindOneBillingSyncLog200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FindOneBillingSyncLog200Response) GetData() FindBillingSyncLog200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret FindBillingSyncLog200ResponseDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindOneBillingSyncLog200Response) GetDataOk() (*FindBillingSyncLog200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FindOneBillingSyncLog200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given FindBillingSyncLog200ResponseDataInner and assigns it to the Data field.
func (o *FindOneBillingSyncLog200Response) SetData(v FindBillingSyncLog200ResponseDataInner) {
	o.Data = &v
}

func (o FindOneBillingSyncLog200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindOneBillingSyncLog200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFindOneBillingSyncLog200Response struct {
	value *FindOneBillingSyncLog200Response
	isSet bool
}

func (v NullableFindOneBillingSyncLog200Response) Get() *FindOneBillingSyncLog200Response {
	return v.value
}

func (v *NullableFindOneBillingSyncLog200Response) Set(val *FindOneBillingSyncLog200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFindOneBillingSyncLog200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFindOneBillingSyncLog200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindOneBillingSyncLog200Response(val *FindOneBillingSyncLog200Response) *NullableFindOneBillingSyncLog200Response {
	return &NullableFindOneBillingSyncLog200Response{value: val, isSet: true}
}

func (v NullableFindOneBillingSyncLog200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindOneBillingSyncLog200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


