/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the FindAlertRule200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindAlertRule200Response{}

// FindAlertRule200Response struct for FindAlertRule200Response
type FindAlertRule200Response struct {
	Data []FindAlertRule200ResponseDataInner `json:"data,omitempty"`
	Meta *FindAccessReviewItem200ResponseMeta `json:"meta,omitempty"`
}

// NewFindAlertRule200Response instantiates a new FindAlertRule200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindAlertRule200Response() *FindAlertRule200Response {
	this := FindAlertRule200Response{}
	return &this
}

// NewFindAlertRule200ResponseWithDefaults instantiates a new FindAlertRule200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindAlertRule200ResponseWithDefaults() *FindAlertRule200Response {
	this := FindAlertRule200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FindAlertRule200Response) GetData() []FindAlertRule200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []FindAlertRule200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindAlertRule200Response) GetDataOk() ([]FindAlertRule200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FindAlertRule200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []FindAlertRule200ResponseDataInner and assigns it to the Data field.
func (o *FindAlertRule200Response) SetData(v []FindAlertRule200ResponseDataInner) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *FindAlertRule200Response) GetMeta() FindAccessReviewItem200ResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret FindAccessReviewItem200ResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindAlertRule200Response) GetMetaOk() (*FindAccessReviewItem200ResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *FindAlertRule200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given FindAccessReviewItem200ResponseMeta and assigns it to the Meta field.
func (o *FindAlertRule200Response) SetMeta(v FindAccessReviewItem200ResponseMeta) {
	o.Meta = &v
}

func (o FindAlertRule200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindAlertRule200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableFindAlertRule200Response struct {
	value *FindAlertRule200Response
	isSet bool
}

func (v NullableFindAlertRule200Response) Get() *FindAlertRule200Response {
	return v.value
}

func (v *NullableFindAlertRule200Response) Set(val *FindAlertRule200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFindAlertRule200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFindAlertRule200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindAlertRule200Response(val *FindAlertRule200Response) *NullableFindAlertRule200Response {
	return &NullableFindAlertRule200Response{value: val, isSet: true}
}

func (v NullableFindAlertRule200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindAlertRule200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


