/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateClusterRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateClusterRequestData{}

// CreateClusterRequestData struct for CreateClusterRequestData
type CreateClusterRequestData struct {
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	UsersPermissionsUser *CreateAccessReviewRequestDataReviewer `json:"users_permissions_user,omitempty"`
	State string `json:"state"`
	ClusterType *string `json:"cluster_type,omitempty"`
	Region *string `json:"region,omitempty"`
	MaxServices *int32 `json:"max_services,omitempty"`
	CurrentServicesCount *int32 `json:"current_services_count,omitempty"`
	MonthlyCost *float32 `json:"monthly_cost,omitempty"`
	// Arbitrary JSON value (object, array, string, number, boolean, or null)
	Metadata interface{} `json:"metadata,omitempty"`
}

type _CreateClusterRequestData CreateClusterRequestData

// NewCreateClusterRequestData instantiates a new CreateClusterRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClusterRequestData(name string, state string) *CreateClusterRequestData {
	this := CreateClusterRequestData{}
	this.Name = name
	this.State = state
	return &this
}

// NewCreateClusterRequestDataWithDefaults instantiates a new CreateClusterRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClusterRequestDataWithDefaults() *CreateClusterRequestData {
	this := CreateClusterRequestData{}
	return &this
}

// GetName returns the Name field value
func (o *CreateClusterRequestData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateClusterRequestData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateClusterRequestData) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateClusterRequestData) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterRequestData) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateClusterRequestData) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateClusterRequestData) SetDescription(v string) {
	o.Description = &v
}

// GetUsersPermissionsUser returns the UsersPermissionsUser field value if set, zero value otherwise.
func (o *CreateClusterRequestData) GetUsersPermissionsUser() CreateAccessReviewRequestDataReviewer {
	if o == nil || IsNil(o.UsersPermissionsUser) {
		var ret CreateAccessReviewRequestDataReviewer
		return ret
	}
	return *o.UsersPermissionsUser
}

// GetUsersPermissionsUserOk returns a tuple with the UsersPermissionsUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterRequestData) GetUsersPermissionsUserOk() (*CreateAccessReviewRequestDataReviewer, bool) {
	if o == nil || IsNil(o.UsersPermissionsUser) {
		return nil, false
	}
	return o.UsersPermissionsUser, true
}

// HasUsersPermissionsUser returns a boolean if a field has been set.
func (o *CreateClusterRequestData) HasUsersPermissionsUser() bool {
	if o != nil && !IsNil(o.UsersPermissionsUser) {
		return true
	}

	return false
}

// SetUsersPermissionsUser gets a reference to the given CreateAccessReviewRequestDataReviewer and assigns it to the UsersPermissionsUser field.
func (o *CreateClusterRequestData) SetUsersPermissionsUser(v CreateAccessReviewRequestDataReviewer) {
	o.UsersPermissionsUser = &v
}

// GetState returns the State field value
func (o *CreateClusterRequestData) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *CreateClusterRequestData) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *CreateClusterRequestData) SetState(v string) {
	o.State = v
}

// GetClusterType returns the ClusterType field value if set, zero value otherwise.
func (o *CreateClusterRequestData) GetClusterType() string {
	if o == nil || IsNil(o.ClusterType) {
		var ret string
		return ret
	}
	return *o.ClusterType
}

// GetClusterTypeOk returns a tuple with the ClusterType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterRequestData) GetClusterTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ClusterType) {
		return nil, false
	}
	return o.ClusterType, true
}

// HasClusterType returns a boolean if a field has been set.
func (o *CreateClusterRequestData) HasClusterType() bool {
	if o != nil && !IsNil(o.ClusterType) {
		return true
	}

	return false
}

// SetClusterType gets a reference to the given string and assigns it to the ClusterType field.
func (o *CreateClusterRequestData) SetClusterType(v string) {
	o.ClusterType = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *CreateClusterRequestData) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterRequestData) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *CreateClusterRequestData) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *CreateClusterRequestData) SetRegion(v string) {
	o.Region = &v
}

// GetMaxServices returns the MaxServices field value if set, zero value otherwise.
func (o *CreateClusterRequestData) GetMaxServices() int32 {
	if o == nil || IsNil(o.MaxServices) {
		var ret int32
		return ret
	}
	return *o.MaxServices
}

// GetMaxServicesOk returns a tuple with the MaxServices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterRequestData) GetMaxServicesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxServices) {
		return nil, false
	}
	return o.MaxServices, true
}

// HasMaxServices returns a boolean if a field has been set.
func (o *CreateClusterRequestData) HasMaxServices() bool {
	if o != nil && !IsNil(o.MaxServices) {
		return true
	}

	return false
}

// SetMaxServices gets a reference to the given int32 and assigns it to the MaxServices field.
func (o *CreateClusterRequestData) SetMaxServices(v int32) {
	o.MaxServices = &v
}

// GetCurrentServicesCount returns the CurrentServicesCount field value if set, zero value otherwise.
func (o *CreateClusterRequestData) GetCurrentServicesCount() int32 {
	if o == nil || IsNil(o.CurrentServicesCount) {
		var ret int32
		return ret
	}
	return *o.CurrentServicesCount
}

// GetCurrentServicesCountOk returns a tuple with the CurrentServicesCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterRequestData) GetCurrentServicesCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentServicesCount) {
		return nil, false
	}
	return o.CurrentServicesCount, true
}

// HasCurrentServicesCount returns a boolean if a field has been set.
func (o *CreateClusterRequestData) HasCurrentServicesCount() bool {
	if o != nil && !IsNil(o.CurrentServicesCount) {
		return true
	}

	return false
}

// SetCurrentServicesCount gets a reference to the given int32 and assigns it to the CurrentServicesCount field.
func (o *CreateClusterRequestData) SetCurrentServicesCount(v int32) {
	o.CurrentServicesCount = &v
}

// GetMonthlyCost returns the MonthlyCost field value if set, zero value otherwise.
func (o *CreateClusterRequestData) GetMonthlyCost() float32 {
	if o == nil || IsNil(o.MonthlyCost) {
		var ret float32
		return ret
	}
	return *o.MonthlyCost
}

// GetMonthlyCostOk returns a tuple with the MonthlyCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterRequestData) GetMonthlyCostOk() (*float32, bool) {
	if o == nil || IsNil(o.MonthlyCost) {
		return nil, false
	}
	return o.MonthlyCost, true
}

// HasMonthlyCost returns a boolean if a field has been set.
func (o *CreateClusterRequestData) HasMonthlyCost() bool {
	if o != nil && !IsNil(o.MonthlyCost) {
		return true
	}

	return false
}

// SetMonthlyCost gets a reference to the given float32 and assigns it to the MonthlyCost field.
func (o *CreateClusterRequestData) SetMonthlyCost(v float32) {
	o.MonthlyCost = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateClusterRequestData) GetMetadata() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateClusterRequestData) GetMetadataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return &o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateClusterRequestData) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given interface{} and assigns it to the Metadata field.
func (o *CreateClusterRequestData) SetMetadata(v interface{}) {
	o.Metadata = v
}

func (o CreateClusterRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateClusterRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.UsersPermissionsUser) {
		toSerialize["users_permissions_user"] = o.UsersPermissionsUser
	}
	toSerialize["state"] = o.State
	if !IsNil(o.ClusterType) {
		toSerialize["cluster_type"] = o.ClusterType
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.MaxServices) {
		toSerialize["max_services"] = o.MaxServices
	}
	if !IsNil(o.CurrentServicesCount) {
		toSerialize["current_services_count"] = o.CurrentServicesCount
	}
	if !IsNil(o.MonthlyCost) {
		toSerialize["monthly_cost"] = o.MonthlyCost
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *CreateClusterRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateClusterRequestData := _CreateClusterRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateClusterRequestData)

	if err != nil {
		return err
	}

	*o = CreateClusterRequestData(varCreateClusterRequestData)

	return err
}

type NullableCreateClusterRequestData struct {
	value *CreateClusterRequestData
	isSet bool
}

func (v NullableCreateClusterRequestData) Get() *CreateClusterRequestData {
	return v.value
}

func (v *NullableCreateClusterRequestData) Set(val *CreateClusterRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClusterRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClusterRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClusterRequestData(val *CreateClusterRequestData) *NullableCreateClusterRequestData {
	return &NullableCreateClusterRequestData{value: val, isSet: true}
}

func (v NullableCreateClusterRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClusterRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


