/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the CreateAgentConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAgentConfigRequest{}

// CreateAgentConfigRequest struct for CreateAgentConfigRequest
type CreateAgentConfigRequest struct {
	Data *CreateAgentConfigRequestData `json:"data,omitempty"`
}

// NewCreateAgentConfigRequest instantiates a new CreateAgentConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAgentConfigRequest() *CreateAgentConfigRequest {
	this := CreateAgentConfigRequest{}
	return &this
}

// NewCreateAgentConfigRequestWithDefaults instantiates a new CreateAgentConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAgentConfigRequestWithDefaults() *CreateAgentConfigRequest {
	this := CreateAgentConfigRequest{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateAgentConfigRequest) GetData() CreateAgentConfigRequestData {
	if o == nil || IsNil(o.Data) {
		var ret CreateAgentConfigRequestData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentConfigRequest) GetDataOk() (*CreateAgentConfigRequestData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateAgentConfigRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CreateAgentConfigRequestData and assigns it to the Data field.
func (o *CreateAgentConfigRequest) SetData(v CreateAgentConfigRequestData) {
	o.Data = &v
}

func (o CreateAgentConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAgentConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateAgentConfigRequest struct {
	value *CreateAgentConfigRequest
	isSet bool
}

func (v NullableCreateAgentConfigRequest) Get() *CreateAgentConfigRequest {
	return v.value
}

func (v *NullableCreateAgentConfigRequest) Set(val *CreateAgentConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAgentConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAgentConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAgentConfigRequest(val *CreateAgentConfigRequest) *NullableCreateAgentConfigRequest {
	return &NullableCreateAgentConfigRequest{value: val, isSet: true}
}

func (v NullableCreateAgentConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAgentConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


