/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the FindOneAiOversightReview200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindOneAiOversightReview200Response{}

// FindOneAiOversightReview200Response struct for FindOneAiOversightReview200Response
type FindOneAiOversightReview200Response struct {
	Data *FindAiOversightReview200ResponseDataInner `json:"data,omitempty"`
}

// NewFindOneAiOversightReview200Response instantiates a new FindOneAiOversightReview200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindOneAiOversightReview200Response() *FindOneAiOversightReview200Response {
	this := FindOneAiOversightReview200Response{}
	return &this
}

// NewFindOneAiOversightReview200ResponseWithDefaults instantiates a new FindOneAiOversightReview200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindOneAiOversightReview200ResponseWithDefaults() *FindOneAiOversightReview200Response {
	this := FindOneAiOversightReview200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FindOneAiOversightReview200Response) GetData() FindAiOversightReview200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret FindAiOversightReview200ResponseDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindOneAiOversightReview200Response) GetDataOk() (*FindAiOversightReview200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FindOneAiOversightReview200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given FindAiOversightReview200ResponseDataInner and assigns it to the Data field.
func (o *FindOneAiOversightReview200Response) SetData(v FindAiOversightReview200ResponseDataInner) {
	o.Data = &v
}

func (o FindOneAiOversightReview200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindOneAiOversightReview200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFindOneAiOversightReview200Response struct {
	value *FindOneAiOversightReview200Response
	isSet bool
}

func (v NullableFindOneAiOversightReview200Response) Get() *FindOneAiOversightReview200Response {
	return v.value
}

func (v *NullableFindOneAiOversightReview200Response) Set(val *FindOneAiOversightReview200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFindOneAiOversightReview200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFindOneAiOversightReview200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindOneAiOversightReview200Response(val *FindOneAiOversightReview200Response) *NullableFindOneAiOversightReview200Response {
	return &NullableFindOneAiOversightReview200Response{value: val, isSet: true}
}

func (v NullableFindOneAiOversightReview200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindOneAiOversightReview200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


