/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the KnowledgeNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KnowledgeNode{}

// KnowledgeNode struct for KnowledgeNode
type KnowledgeNode struct {
	NodeType string `json:"node_type"`
	// Human-readable identifier, e.g. 'backend:1337', 'ec2-i-abc123', 'postgres-prod'.
	Label string `json:"label"`
	// Internal Strapi documentId or cloud provider resource ID.
	ResourceId *string `json:"resource_id,omitempty"`
	// Strapi content-type slug or cloud resource kind, e.g. 'cloud-instance', 'organisation-member', 'dns-zone'.
	ResourceType *string `json:"resource_type,omitempty"`
	// Arbitrary key-value metadata for this node (provider, region, tags, etc.).
	Properties interface{} `json:"properties,omitempty"`
	LastSeenAt *time.Time `json:"last_seen_at,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
	Organisation *CreateAccessReviewRequestDataReviewer `json:"organisation,omitempty"`
}

type _KnowledgeNode KnowledgeNode

// NewKnowledgeNode instantiates a new KnowledgeNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKnowledgeNode(nodeType string, label string) *KnowledgeNode {
	this := KnowledgeNode{}
	this.NodeType = nodeType
	this.Label = label
	return &this
}

// NewKnowledgeNodeWithDefaults instantiates a new KnowledgeNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKnowledgeNodeWithDefaults() *KnowledgeNode {
	this := KnowledgeNode{}
	return &this
}

// GetNodeType returns the NodeType field value
func (o *KnowledgeNode) GetNodeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeType
}

// GetNodeTypeOk returns a tuple with the NodeType field value
// and a boolean to check if the value has been set.
func (o *KnowledgeNode) GetNodeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeType, true
}

// SetNodeType sets field value
func (o *KnowledgeNode) SetNodeType(v string) {
	o.NodeType = v
}

// GetLabel returns the Label field value
func (o *KnowledgeNode) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *KnowledgeNode) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *KnowledgeNode) SetLabel(v string) {
	o.Label = v
}

// GetResourceId returns the ResourceId field value if set, zero value otherwise.
func (o *KnowledgeNode) GetResourceId() string {
	if o == nil || IsNil(o.ResourceId) {
		var ret string
		return ret
	}
	return *o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnowledgeNode) GetResourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceId) {
		return nil, false
	}
	return o.ResourceId, true
}

// HasResourceId returns a boolean if a field has been set.
func (o *KnowledgeNode) HasResourceId() bool {
	if o != nil && !IsNil(o.ResourceId) {
		return true
	}

	return false
}

// SetResourceId gets a reference to the given string and assigns it to the ResourceId field.
func (o *KnowledgeNode) SetResourceId(v string) {
	o.ResourceId = &v
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise.
func (o *KnowledgeNode) GetResourceType() string {
	if o == nil || IsNil(o.ResourceType) {
		var ret string
		return ret
	}
	return *o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnowledgeNode) GetResourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceType) {
		return nil, false
	}
	return o.ResourceType, true
}

// HasResourceType returns a boolean if a field has been set.
func (o *KnowledgeNode) HasResourceType() bool {
	if o != nil && !IsNil(o.ResourceType) {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given string and assigns it to the ResourceType field.
func (o *KnowledgeNode) SetResourceType(v string) {
	o.ResourceType = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KnowledgeNode) GetProperties() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KnowledgeNode) GetPropertiesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return &o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *KnowledgeNode) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given interface{} and assigns it to the Properties field.
func (o *KnowledgeNode) SetProperties(v interface{}) {
	o.Properties = v
}

// GetLastSeenAt returns the LastSeenAt field value if set, zero value otherwise.
func (o *KnowledgeNode) GetLastSeenAt() time.Time {
	if o == nil || IsNil(o.LastSeenAt) {
		var ret time.Time
		return ret
	}
	return *o.LastSeenAt
}

// GetLastSeenAtOk returns a tuple with the LastSeenAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnowledgeNode) GetLastSeenAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastSeenAt) {
		return nil, false
	}
	return o.LastSeenAt, true
}

// HasLastSeenAt returns a boolean if a field has been set.
func (o *KnowledgeNode) HasLastSeenAt() bool {
	if o != nil && !IsNil(o.LastSeenAt) {
		return true
	}

	return false
}

// SetLastSeenAt gets a reference to the given time.Time and assigns it to the LastSeenAt field.
func (o *KnowledgeNode) SetLastSeenAt(v time.Time) {
	o.LastSeenAt = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *KnowledgeNode) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnowledgeNode) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *KnowledgeNode) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *KnowledgeNode) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetOrganisation returns the Organisation field value if set, zero value otherwise.
func (o *KnowledgeNode) GetOrganisation() CreateAccessReviewRequestDataReviewer {
	if o == nil || IsNil(o.Organisation) {
		var ret CreateAccessReviewRequestDataReviewer
		return ret
	}
	return *o.Organisation
}

// GetOrganisationOk returns a tuple with the Organisation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnowledgeNode) GetOrganisationOk() (*CreateAccessReviewRequestDataReviewer, bool) {
	if o == nil || IsNil(o.Organisation) {
		return nil, false
	}
	return o.Organisation, true
}

// HasOrganisation returns a boolean if a field has been set.
func (o *KnowledgeNode) HasOrganisation() bool {
	if o != nil && !IsNil(o.Organisation) {
		return true
	}

	return false
}

// SetOrganisation gets a reference to the given CreateAccessReviewRequestDataReviewer and assigns it to the Organisation field.
func (o *KnowledgeNode) SetOrganisation(v CreateAccessReviewRequestDataReviewer) {
	o.Organisation = &v
}

func (o KnowledgeNode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KnowledgeNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["node_type"] = o.NodeType
	toSerialize["label"] = o.Label
	if !IsNil(o.ResourceId) {
		toSerialize["resource_id"] = o.ResourceId
	}
	if !IsNil(o.ResourceType) {
		toSerialize["resource_type"] = o.ResourceType
	}
	if o.Properties != nil {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.LastSeenAt) {
		toSerialize["last_seen_at"] = o.LastSeenAt
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.Organisation) {
		toSerialize["organisation"] = o.Organisation
	}
	return toSerialize, nil
}

func (o *KnowledgeNode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"node_type",
		"label",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKnowledgeNode := _KnowledgeNode{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKnowledgeNode)

	if err != nil {
		return err
	}

	*o = KnowledgeNode(varKnowledgeNode)

	return err
}

type NullableKnowledgeNode struct {
	value *KnowledgeNode
	isSet bool
}

func (v NullableKnowledgeNode) Get() *KnowledgeNode {
	return v.value
}

func (v *NullableKnowledgeNode) Set(val *KnowledgeNode) {
	v.value = val
	v.isSet = true
}

func (v NullableKnowledgeNode) IsSet() bool {
	return v.isSet
}

func (v *NullableKnowledgeNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnowledgeNode(val *KnowledgeNode) *NullableKnowledgeNode {
	return &NullableKnowledgeNode{value: val, isSet: true}
}

func (v NullableKnowledgeNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnowledgeNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


