/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the CreateRateLimitPolicy200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRateLimitPolicy200Response{}

// CreateRateLimitPolicy200Response struct for CreateRateLimitPolicy200Response
type CreateRateLimitPolicy200Response struct {
	Data *FindRateLimitPolicy200ResponseDataInner `json:"data,omitempty"`
}

// NewCreateRateLimitPolicy200Response instantiates a new CreateRateLimitPolicy200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRateLimitPolicy200Response() *CreateRateLimitPolicy200Response {
	this := CreateRateLimitPolicy200Response{}
	return &this
}

// NewCreateRateLimitPolicy200ResponseWithDefaults instantiates a new CreateRateLimitPolicy200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRateLimitPolicy200ResponseWithDefaults() *CreateRateLimitPolicy200Response {
	this := CreateRateLimitPolicy200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateRateLimitPolicy200Response) GetData() FindRateLimitPolicy200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret FindRateLimitPolicy200ResponseDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRateLimitPolicy200Response) GetDataOk() (*FindRateLimitPolicy200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateRateLimitPolicy200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given FindRateLimitPolicy200ResponseDataInner and assigns it to the Data field.
func (o *CreateRateLimitPolicy200Response) SetData(v FindRateLimitPolicy200ResponseDataInner) {
	o.Data = &v
}

func (o CreateRateLimitPolicy200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRateLimitPolicy200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateRateLimitPolicy200Response struct {
	value *CreateRateLimitPolicy200Response
	isSet bool
}

func (v NullableCreateRateLimitPolicy200Response) Get() *CreateRateLimitPolicy200Response {
	return v.value
}

func (v *NullableCreateRateLimitPolicy200Response) Set(val *CreateRateLimitPolicy200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRateLimitPolicy200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRateLimitPolicy200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRateLimitPolicy200Response(val *CreateRateLimitPolicy200Response) *NullableCreateRateLimitPolicy200Response {
	return &NullableCreateRateLimitPolicy200Response{value: val, isSet: true}
}

func (v NullableCreateRateLimitPolicy200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRateLimitPolicy200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


