/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the CreateAgentUpdatePolicy200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAgentUpdatePolicy200Response{}

// CreateAgentUpdatePolicy200Response struct for CreateAgentUpdatePolicy200Response
type CreateAgentUpdatePolicy200Response struct {
	Data *FindAgentUpdatePolicy200ResponseDataInner `json:"data,omitempty"`
}

// NewCreateAgentUpdatePolicy200Response instantiates a new CreateAgentUpdatePolicy200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAgentUpdatePolicy200Response() *CreateAgentUpdatePolicy200Response {
	this := CreateAgentUpdatePolicy200Response{}
	return &this
}

// NewCreateAgentUpdatePolicy200ResponseWithDefaults instantiates a new CreateAgentUpdatePolicy200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAgentUpdatePolicy200ResponseWithDefaults() *CreateAgentUpdatePolicy200Response {
	this := CreateAgentUpdatePolicy200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateAgentUpdatePolicy200Response) GetData() FindAgentUpdatePolicy200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret FindAgentUpdatePolicy200ResponseDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentUpdatePolicy200Response) GetDataOk() (*FindAgentUpdatePolicy200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateAgentUpdatePolicy200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given FindAgentUpdatePolicy200ResponseDataInner and assigns it to the Data field.
func (o *CreateAgentUpdatePolicy200Response) SetData(v FindAgentUpdatePolicy200ResponseDataInner) {
	o.Data = &v
}

func (o CreateAgentUpdatePolicy200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAgentUpdatePolicy200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateAgentUpdatePolicy200Response struct {
	value *CreateAgentUpdatePolicy200Response
	isSet bool
}

func (v NullableCreateAgentUpdatePolicy200Response) Get() *CreateAgentUpdatePolicy200Response {
	return v.value
}

func (v *NullableCreateAgentUpdatePolicy200Response) Set(val *CreateAgentUpdatePolicy200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAgentUpdatePolicy200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAgentUpdatePolicy200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAgentUpdatePolicy200Response(val *CreateAgentUpdatePolicy200Response) *NullableCreateAgentUpdatePolicy200Response {
	return &NullableCreateAgentUpdatePolicy200Response{value: val, isSet: true}
}

func (v NullableCreateAgentUpdatePolicy200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAgentUpdatePolicy200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


