/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the FindOneCostForecast200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindOneCostForecast200Response{}

// FindOneCostForecast200Response struct for FindOneCostForecast200Response
type FindOneCostForecast200Response struct {
	Data *FindCostForecast200ResponseDataInner `json:"data,omitempty"`
}

// NewFindOneCostForecast200Response instantiates a new FindOneCostForecast200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindOneCostForecast200Response() *FindOneCostForecast200Response {
	this := FindOneCostForecast200Response{}
	return &this
}

// NewFindOneCostForecast200ResponseWithDefaults instantiates a new FindOneCostForecast200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindOneCostForecast200ResponseWithDefaults() *FindOneCostForecast200Response {
	this := FindOneCostForecast200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FindOneCostForecast200Response) GetData() FindCostForecast200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret FindCostForecast200ResponseDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindOneCostForecast200Response) GetDataOk() (*FindCostForecast200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FindOneCostForecast200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given FindCostForecast200ResponseDataInner and assigns it to the Data field.
func (o *FindOneCostForecast200Response) SetData(v FindCostForecast200ResponseDataInner) {
	o.Data = &v
}

func (o FindOneCostForecast200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindOneCostForecast200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFindOneCostForecast200Response struct {
	value *FindOneCostForecast200Response
	isSet bool
}

func (v NullableFindOneCostForecast200Response) Get() *FindOneCostForecast200Response {
	return v.value
}

func (v *NullableFindOneCostForecast200Response) Set(val *FindOneCostForecast200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFindOneCostForecast200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFindOneCostForecast200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindOneCostForecast200Response(val *FindOneCostForecast200Response) *NullableFindOneCostForecast200Response {
	return &NullableFindOneCostForecast200Response{value: val, isSet: true}
}

func (v NullableFindOneCostForecast200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindOneCostForecast200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


