/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDnsRecordRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDnsRecordRequestData{}

// CreateDnsRecordRequestData struct for CreateDnsRecordRequestData
type CreateDnsRecordRequestData struct {
	Zone *CreateAccessReviewRequestDataReviewer `json:"zone,omitempty"`
	Type string `json:"type"`
	// Relative record name (@, www, mail, ...). @ denotes the zone apex.
	Name string `json:"name"`
	// Record target value (IP address, domain, TXT content, etc.).
	Value string `json:"value"`
	Ttl *int32 `json:"ttl,omitempty"`
	Weight *int32 `json:"weight,omitempty"`
	// Priority for MX and SRV records.
	Priority *int32 `json:"priority,omitempty"`
	GeoLocation *string `json:"geo_location,omitempty"`
	// Provider-side record identifier (for update/delete operations).
	ProviderRecordId *string `json:"provider_record_id,omitempty"`
	Organisation *CreateAccessReviewRequestDataReviewer `json:"organisation,omitempty"`
}

type _CreateDnsRecordRequestData CreateDnsRecordRequestData

// NewCreateDnsRecordRequestData instantiates a new CreateDnsRecordRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDnsRecordRequestData(type_ string, name string, value string) *CreateDnsRecordRequestData {
	this := CreateDnsRecordRequestData{}
	this.Type = type_
	this.Name = name
	this.Value = value
	return &this
}

// NewCreateDnsRecordRequestDataWithDefaults instantiates a new CreateDnsRecordRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDnsRecordRequestDataWithDefaults() *CreateDnsRecordRequestData {
	this := CreateDnsRecordRequestData{}
	return &this
}

// GetZone returns the Zone field value if set, zero value otherwise.
func (o *CreateDnsRecordRequestData) GetZone() CreateAccessReviewRequestDataReviewer {
	if o == nil || IsNil(o.Zone) {
		var ret CreateAccessReviewRequestDataReviewer
		return ret
	}
	return *o.Zone
}

// GetZoneOk returns a tuple with the Zone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDnsRecordRequestData) GetZoneOk() (*CreateAccessReviewRequestDataReviewer, bool) {
	if o == nil || IsNil(o.Zone) {
		return nil, false
	}
	return o.Zone, true
}

// HasZone returns a boolean if a field has been set.
func (o *CreateDnsRecordRequestData) HasZone() bool {
	if o != nil && !IsNil(o.Zone) {
		return true
	}

	return false
}

// SetZone gets a reference to the given CreateAccessReviewRequestDataReviewer and assigns it to the Zone field.
func (o *CreateDnsRecordRequestData) SetZone(v CreateAccessReviewRequestDataReviewer) {
	o.Zone = &v
}

// GetType returns the Type field value
func (o *CreateDnsRecordRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateDnsRecordRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateDnsRecordRequestData) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value
func (o *CreateDnsRecordRequestData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateDnsRecordRequestData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateDnsRecordRequestData) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *CreateDnsRecordRequestData) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CreateDnsRecordRequestData) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CreateDnsRecordRequestData) SetValue(v string) {
	o.Value = v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *CreateDnsRecordRequestData) GetTtl() int32 {
	if o == nil || IsNil(o.Ttl) {
		var ret int32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDnsRecordRequestData) GetTtlOk() (*int32, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *CreateDnsRecordRequestData) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int32 and assigns it to the Ttl field.
func (o *CreateDnsRecordRequestData) SetTtl(v int32) {
	o.Ttl = &v
}

// GetWeight returns the Weight field value if set, zero value otherwise.
func (o *CreateDnsRecordRequestData) GetWeight() int32 {
	if o == nil || IsNil(o.Weight) {
		var ret int32
		return ret
	}
	return *o.Weight
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDnsRecordRequestData) GetWeightOk() (*int32, bool) {
	if o == nil || IsNil(o.Weight) {
		return nil, false
	}
	return o.Weight, true
}

// HasWeight returns a boolean if a field has been set.
func (o *CreateDnsRecordRequestData) HasWeight() bool {
	if o != nil && !IsNil(o.Weight) {
		return true
	}

	return false
}

// SetWeight gets a reference to the given int32 and assigns it to the Weight field.
func (o *CreateDnsRecordRequestData) SetWeight(v int32) {
	o.Weight = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *CreateDnsRecordRequestData) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDnsRecordRequestData) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *CreateDnsRecordRequestData) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *CreateDnsRecordRequestData) SetPriority(v int32) {
	o.Priority = &v
}

// GetGeoLocation returns the GeoLocation field value if set, zero value otherwise.
func (o *CreateDnsRecordRequestData) GetGeoLocation() string {
	if o == nil || IsNil(o.GeoLocation) {
		var ret string
		return ret
	}
	return *o.GeoLocation
}

// GetGeoLocationOk returns a tuple with the GeoLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDnsRecordRequestData) GetGeoLocationOk() (*string, bool) {
	if o == nil || IsNil(o.GeoLocation) {
		return nil, false
	}
	return o.GeoLocation, true
}

// HasGeoLocation returns a boolean if a field has been set.
func (o *CreateDnsRecordRequestData) HasGeoLocation() bool {
	if o != nil && !IsNil(o.GeoLocation) {
		return true
	}

	return false
}

// SetGeoLocation gets a reference to the given string and assigns it to the GeoLocation field.
func (o *CreateDnsRecordRequestData) SetGeoLocation(v string) {
	o.GeoLocation = &v
}

// GetProviderRecordId returns the ProviderRecordId field value if set, zero value otherwise.
func (o *CreateDnsRecordRequestData) GetProviderRecordId() string {
	if o == nil || IsNil(o.ProviderRecordId) {
		var ret string
		return ret
	}
	return *o.ProviderRecordId
}

// GetProviderRecordIdOk returns a tuple with the ProviderRecordId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDnsRecordRequestData) GetProviderRecordIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderRecordId) {
		return nil, false
	}
	return o.ProviderRecordId, true
}

// HasProviderRecordId returns a boolean if a field has been set.
func (o *CreateDnsRecordRequestData) HasProviderRecordId() bool {
	if o != nil && !IsNil(o.ProviderRecordId) {
		return true
	}

	return false
}

// SetProviderRecordId gets a reference to the given string and assigns it to the ProviderRecordId field.
func (o *CreateDnsRecordRequestData) SetProviderRecordId(v string) {
	o.ProviderRecordId = &v
}

// GetOrganisation returns the Organisation field value if set, zero value otherwise.
func (o *CreateDnsRecordRequestData) GetOrganisation() CreateAccessReviewRequestDataReviewer {
	if o == nil || IsNil(o.Organisation) {
		var ret CreateAccessReviewRequestDataReviewer
		return ret
	}
	return *o.Organisation
}

// GetOrganisationOk returns a tuple with the Organisation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDnsRecordRequestData) GetOrganisationOk() (*CreateAccessReviewRequestDataReviewer, bool) {
	if o == nil || IsNil(o.Organisation) {
		return nil, false
	}
	return o.Organisation, true
}

// HasOrganisation returns a boolean if a field has been set.
func (o *CreateDnsRecordRequestData) HasOrganisation() bool {
	if o != nil && !IsNil(o.Organisation) {
		return true
	}

	return false
}

// SetOrganisation gets a reference to the given CreateAccessReviewRequestDataReviewer and assigns it to the Organisation field.
func (o *CreateDnsRecordRequestData) SetOrganisation(v CreateAccessReviewRequestDataReviewer) {
	o.Organisation = &v
}

func (o CreateDnsRecordRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDnsRecordRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Zone) {
		toSerialize["zone"] = o.Zone
	}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	if !IsNil(o.Weight) {
		toSerialize["weight"] = o.Weight
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.GeoLocation) {
		toSerialize["geo_location"] = o.GeoLocation
	}
	if !IsNil(o.ProviderRecordId) {
		toSerialize["provider_record_id"] = o.ProviderRecordId
	}
	if !IsNil(o.Organisation) {
		toSerialize["organisation"] = o.Organisation
	}
	return toSerialize, nil
}

func (o *CreateDnsRecordRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDnsRecordRequestData := _CreateDnsRecordRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDnsRecordRequestData)

	if err != nil {
		return err
	}

	*o = CreateDnsRecordRequestData(varCreateDnsRecordRequestData)

	return err
}

type NullableCreateDnsRecordRequestData struct {
	value *CreateDnsRecordRequestData
	isSet bool
}

func (v NullableCreateDnsRecordRequestData) Get() *CreateDnsRecordRequestData {
	return v.value
}

func (v *NullableCreateDnsRecordRequestData) Set(val *CreateDnsRecordRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDnsRecordRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDnsRecordRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDnsRecordRequestData(val *CreateDnsRecordRequestData) *NullableCreateDnsRecordRequestData {
	return &NullableCreateDnsRecordRequestData{value: val, isSet: true}
}

func (v NullableCreateDnsRecordRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDnsRecordRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


