/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the CreatePatchRunRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePatchRunRequest{}

// CreatePatchRunRequest struct for CreatePatchRunRequest
type CreatePatchRunRequest struct {
	Data *CreatePatchRunRequestData `json:"data,omitempty"`
}

// NewCreatePatchRunRequest instantiates a new CreatePatchRunRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePatchRunRequest() *CreatePatchRunRequest {
	this := CreatePatchRunRequest{}
	return &this
}

// NewCreatePatchRunRequestWithDefaults instantiates a new CreatePatchRunRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePatchRunRequestWithDefaults() *CreatePatchRunRequest {
	this := CreatePatchRunRequest{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreatePatchRunRequest) GetData() CreatePatchRunRequestData {
	if o == nil || IsNil(o.Data) {
		var ret CreatePatchRunRequestData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePatchRunRequest) GetDataOk() (*CreatePatchRunRequestData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreatePatchRunRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CreatePatchRunRequestData and assigns it to the Data field.
func (o *CreatePatchRunRequest) SetData(v CreatePatchRunRequestData) {
	o.Data = &v
}

func (o CreatePatchRunRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePatchRunRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreatePatchRunRequest struct {
	value *CreatePatchRunRequest
	isSet bool
}

func (v NullableCreatePatchRunRequest) Get() *CreatePatchRunRequest {
	return v.value
}

func (v *NullableCreatePatchRunRequest) Set(val *CreatePatchRunRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePatchRunRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePatchRunRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePatchRunRequest(val *CreatePatchRunRequest) *NullableCreatePatchRunRequest {
	return &NullableCreatePatchRunRequest{value: val, isSet: true}
}

func (v NullableCreatePatchRunRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePatchRunRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


