/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the CreateCloudConnectorStatusRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCloudConnectorStatusRequest{}

// CreateCloudConnectorStatusRequest struct for CreateCloudConnectorStatusRequest
type CreateCloudConnectorStatusRequest struct {
	Data *CreateCloudConnectorStatusRequestData `json:"data,omitempty"`
}

// NewCreateCloudConnectorStatusRequest instantiates a new CreateCloudConnectorStatusRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCloudConnectorStatusRequest() *CreateCloudConnectorStatusRequest {
	this := CreateCloudConnectorStatusRequest{}
	return &this
}

// NewCreateCloudConnectorStatusRequestWithDefaults instantiates a new CreateCloudConnectorStatusRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCloudConnectorStatusRequestWithDefaults() *CreateCloudConnectorStatusRequest {
	this := CreateCloudConnectorStatusRequest{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateCloudConnectorStatusRequest) GetData() CreateCloudConnectorStatusRequestData {
	if o == nil || IsNil(o.Data) {
		var ret CreateCloudConnectorStatusRequestData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCloudConnectorStatusRequest) GetDataOk() (*CreateCloudConnectorStatusRequestData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateCloudConnectorStatusRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CreateCloudConnectorStatusRequestData and assigns it to the Data field.
func (o *CreateCloudConnectorStatusRequest) SetData(v CreateCloudConnectorStatusRequestData) {
	o.Data = &v
}

func (o CreateCloudConnectorStatusRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCloudConnectorStatusRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateCloudConnectorStatusRequest struct {
	value *CreateCloudConnectorStatusRequest
	isSet bool
}

func (v NullableCreateCloudConnectorStatusRequest) Get() *CreateCloudConnectorStatusRequest {
	return v.value
}

func (v *NullableCreateCloudConnectorStatusRequest) Set(val *CreateCloudConnectorStatusRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCloudConnectorStatusRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCloudConnectorStatusRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCloudConnectorStatusRequest(val *CreateCloudConnectorStatusRequest) *NullableCreateCloudConnectorStatusRequest {
	return &NullableCreateCloudConnectorStatusRequest{value: val, isSet: true}
}

func (v NullableCreateCloudConnectorStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCloudConnectorStatusRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


