/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the CreateApprovalRequest200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateApprovalRequest200Response{}

// CreateApprovalRequest200Response struct for CreateApprovalRequest200Response
type CreateApprovalRequest200Response struct {
	Data *FindApprovalRequest200ResponseDataInner `json:"data,omitempty"`
}

// NewCreateApprovalRequest200Response instantiates a new CreateApprovalRequest200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateApprovalRequest200Response() *CreateApprovalRequest200Response {
	this := CreateApprovalRequest200Response{}
	return &this
}

// NewCreateApprovalRequest200ResponseWithDefaults instantiates a new CreateApprovalRequest200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateApprovalRequest200ResponseWithDefaults() *CreateApprovalRequest200Response {
	this := CreateApprovalRequest200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateApprovalRequest200Response) GetData() FindApprovalRequest200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret FindApprovalRequest200ResponseDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApprovalRequest200Response) GetDataOk() (*FindApprovalRequest200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateApprovalRequest200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given FindApprovalRequest200ResponseDataInner and assigns it to the Data field.
func (o *CreateApprovalRequest200Response) SetData(v FindApprovalRequest200ResponseDataInner) {
	o.Data = &v
}

func (o CreateApprovalRequest200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateApprovalRequest200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateApprovalRequest200Response struct {
	value *CreateApprovalRequest200Response
	isSet bool
}

func (v NullableCreateApprovalRequest200Response) Get() *CreateApprovalRequest200Response {
	return v.value
}

func (v *NullableCreateApprovalRequest200Response) Set(val *CreateApprovalRequest200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApprovalRequest200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApprovalRequest200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApprovalRequest200Response(val *CreateApprovalRequest200Response) *NullableCreateApprovalRequest200Response {
	return &NullableCreateApprovalRequest200Response{value: val, isSet: true}
}

func (v NullableCreateApprovalRequest200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApprovalRequest200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


