/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the CreateCrossCloudConnectionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCrossCloudConnectionRequest{}

// CreateCrossCloudConnectionRequest struct for CreateCrossCloudConnectionRequest
type CreateCrossCloudConnectionRequest struct {
	Data *CreateCrossCloudConnectionRequestData `json:"data,omitempty"`
}

// NewCreateCrossCloudConnectionRequest instantiates a new CreateCrossCloudConnectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCrossCloudConnectionRequest() *CreateCrossCloudConnectionRequest {
	this := CreateCrossCloudConnectionRequest{}
	return &this
}

// NewCreateCrossCloudConnectionRequestWithDefaults instantiates a new CreateCrossCloudConnectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCrossCloudConnectionRequestWithDefaults() *CreateCrossCloudConnectionRequest {
	this := CreateCrossCloudConnectionRequest{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateCrossCloudConnectionRequest) GetData() CreateCrossCloudConnectionRequestData {
	if o == nil || IsNil(o.Data) {
		var ret CreateCrossCloudConnectionRequestData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCrossCloudConnectionRequest) GetDataOk() (*CreateCrossCloudConnectionRequestData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateCrossCloudConnectionRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CreateCrossCloudConnectionRequestData and assigns it to the Data field.
func (o *CreateCrossCloudConnectionRequest) SetData(v CreateCrossCloudConnectionRequestData) {
	o.Data = &v
}

func (o CreateCrossCloudConnectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCrossCloudConnectionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateCrossCloudConnectionRequest struct {
	value *CreateCrossCloudConnectionRequest
	isSet bool
}

func (v NullableCreateCrossCloudConnectionRequest) Get() *CreateCrossCloudConnectionRequest {
	return v.value
}

func (v *NullableCreateCrossCloudConnectionRequest) Set(val *CreateCrossCloudConnectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCrossCloudConnectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCrossCloudConnectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCrossCloudConnectionRequest(val *CreateCrossCloudConnectionRequest) *NullableCreateCrossCloudConnectionRequest {
	return &NullableCreateCrossCloudConnectionRequest{value: val, isSet: true}
}

func (v NullableCreateCrossCloudConnectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCrossCloudConnectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


