/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the CreateCloudConnectorStatus200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCloudConnectorStatus200Response{}

// CreateCloudConnectorStatus200Response struct for CreateCloudConnectorStatus200Response
type CreateCloudConnectorStatus200Response struct {
	Data *FindCloudConnectorStatus200ResponseDataInner `json:"data,omitempty"`
}

// NewCreateCloudConnectorStatus200Response instantiates a new CreateCloudConnectorStatus200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCloudConnectorStatus200Response() *CreateCloudConnectorStatus200Response {
	this := CreateCloudConnectorStatus200Response{}
	return &this
}

// NewCreateCloudConnectorStatus200ResponseWithDefaults instantiates a new CreateCloudConnectorStatus200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCloudConnectorStatus200ResponseWithDefaults() *CreateCloudConnectorStatus200Response {
	this := CreateCloudConnectorStatus200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateCloudConnectorStatus200Response) GetData() FindCloudConnectorStatus200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret FindCloudConnectorStatus200ResponseDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCloudConnectorStatus200Response) GetDataOk() (*FindCloudConnectorStatus200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateCloudConnectorStatus200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given FindCloudConnectorStatus200ResponseDataInner and assigns it to the Data field.
func (o *CreateCloudConnectorStatus200Response) SetData(v FindCloudConnectorStatus200ResponseDataInner) {
	o.Data = &v
}

func (o CreateCloudConnectorStatus200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCloudConnectorStatus200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateCloudConnectorStatus200Response struct {
	value *CreateCloudConnectorStatus200Response
	isSet bool
}

func (v NullableCreateCloudConnectorStatus200Response) Get() *CreateCloudConnectorStatus200Response {
	return v.value
}

func (v *NullableCreateCloudConnectorStatus200Response) Set(val *CreateCloudConnectorStatus200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCloudConnectorStatus200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCloudConnectorStatus200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCloudConnectorStatus200Response(val *CreateCloudConnectorStatus200Response) *NullableCreateCloudConnectorStatus200Response {
	return &NullableCreateCloudConnectorStatus200Response{value: val, isSet: true}
}

func (v NullableCreateCloudConnectorStatus200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCloudConnectorStatus200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


