/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAccountTypeRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAccountTypeRequestData{}

// CreateAccountTypeRequestData struct for CreateAccountTypeRequestData
type CreateAccountTypeRequestData struct {
	Type string `json:"type"`
	Description *string `json:"description,omitempty"`
	Price int32 `json:"price"`
	LimitUser *int32 `json:"limit_user,omitempty"`
	PublicCloud bool `json:"public_cloud"`
	Users *CreateAccessReviewRequestDataReviewer `json:"users,omitempty"`
	Organisations *CreateAccessReviewRequestDataReviewer `json:"organisations,omitempty"`
}

type _CreateAccountTypeRequestData CreateAccountTypeRequestData

// NewCreateAccountTypeRequestData instantiates a new CreateAccountTypeRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAccountTypeRequestData(type_ string, price int32, publicCloud bool) *CreateAccountTypeRequestData {
	this := CreateAccountTypeRequestData{}
	this.Type = type_
	this.Price = price
	this.PublicCloud = publicCloud
	return &this
}

// NewCreateAccountTypeRequestDataWithDefaults instantiates a new CreateAccountTypeRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAccountTypeRequestDataWithDefaults() *CreateAccountTypeRequestData {
	this := CreateAccountTypeRequestData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateAccountTypeRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateAccountTypeRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateAccountTypeRequestData) SetType(v string) {
	o.Type = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateAccountTypeRequestData) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountTypeRequestData) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateAccountTypeRequestData) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateAccountTypeRequestData) SetDescription(v string) {
	o.Description = &v
}

// GetPrice returns the Price field value
func (o *CreateAccountTypeRequestData) GetPrice() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *CreateAccountTypeRequestData) GetPriceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *CreateAccountTypeRequestData) SetPrice(v int32) {
	o.Price = v
}

// GetLimitUser returns the LimitUser field value if set, zero value otherwise.
func (o *CreateAccountTypeRequestData) GetLimitUser() int32 {
	if o == nil || IsNil(o.LimitUser) {
		var ret int32
		return ret
	}
	return *o.LimitUser
}

// GetLimitUserOk returns a tuple with the LimitUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountTypeRequestData) GetLimitUserOk() (*int32, bool) {
	if o == nil || IsNil(o.LimitUser) {
		return nil, false
	}
	return o.LimitUser, true
}

// HasLimitUser returns a boolean if a field has been set.
func (o *CreateAccountTypeRequestData) HasLimitUser() bool {
	if o != nil && !IsNil(o.LimitUser) {
		return true
	}

	return false
}

// SetLimitUser gets a reference to the given int32 and assigns it to the LimitUser field.
func (o *CreateAccountTypeRequestData) SetLimitUser(v int32) {
	o.LimitUser = &v
}

// GetPublicCloud returns the PublicCloud field value
func (o *CreateAccountTypeRequestData) GetPublicCloud() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PublicCloud
}

// GetPublicCloudOk returns a tuple with the PublicCloud field value
// and a boolean to check if the value has been set.
func (o *CreateAccountTypeRequestData) GetPublicCloudOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicCloud, true
}

// SetPublicCloud sets field value
func (o *CreateAccountTypeRequestData) SetPublicCloud(v bool) {
	o.PublicCloud = v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *CreateAccountTypeRequestData) GetUsers() CreateAccessReviewRequestDataReviewer {
	if o == nil || IsNil(o.Users) {
		var ret CreateAccessReviewRequestDataReviewer
		return ret
	}
	return *o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountTypeRequestData) GetUsersOk() (*CreateAccessReviewRequestDataReviewer, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *CreateAccountTypeRequestData) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given CreateAccessReviewRequestDataReviewer and assigns it to the Users field.
func (o *CreateAccountTypeRequestData) SetUsers(v CreateAccessReviewRequestDataReviewer) {
	o.Users = &v
}

// GetOrganisations returns the Organisations field value if set, zero value otherwise.
func (o *CreateAccountTypeRequestData) GetOrganisations() CreateAccessReviewRequestDataReviewer {
	if o == nil || IsNil(o.Organisations) {
		var ret CreateAccessReviewRequestDataReviewer
		return ret
	}
	return *o.Organisations
}

// GetOrganisationsOk returns a tuple with the Organisations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountTypeRequestData) GetOrganisationsOk() (*CreateAccessReviewRequestDataReviewer, bool) {
	if o == nil || IsNil(o.Organisations) {
		return nil, false
	}
	return o.Organisations, true
}

// HasOrganisations returns a boolean if a field has been set.
func (o *CreateAccountTypeRequestData) HasOrganisations() bool {
	if o != nil && !IsNil(o.Organisations) {
		return true
	}

	return false
}

// SetOrganisations gets a reference to the given CreateAccessReviewRequestDataReviewer and assigns it to the Organisations field.
func (o *CreateAccountTypeRequestData) SetOrganisations(v CreateAccessReviewRequestDataReviewer) {
	o.Organisations = &v
}

func (o CreateAccountTypeRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAccountTypeRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["price"] = o.Price
	if !IsNil(o.LimitUser) {
		toSerialize["limit_user"] = o.LimitUser
	}
	toSerialize["public_cloud"] = o.PublicCloud
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	if !IsNil(o.Organisations) {
		toSerialize["organisations"] = o.Organisations
	}
	return toSerialize, nil
}

func (o *CreateAccountTypeRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"price",
		"public_cloud",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAccountTypeRequestData := _CreateAccountTypeRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAccountTypeRequestData)

	if err != nil {
		return err
	}

	*o = CreateAccountTypeRequestData(varCreateAccountTypeRequestData)

	return err
}

type NullableCreateAccountTypeRequestData struct {
	value *CreateAccountTypeRequestData
	isSet bool
}

func (v NullableCreateAccountTypeRequestData) Get() *CreateAccountTypeRequestData {
	return v.value
}

func (v *NullableCreateAccountTypeRequestData) Set(val *CreateAccountTypeRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccountTypeRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccountTypeRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccountTypeRequestData(val *CreateAccountTypeRequestData) *NullableCreateAccountTypeRequestData {
	return &NullableCreateAccountTypeRequestData{value: val, isSet: true}
}

func (v NullableCreateAccountTypeRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccountTypeRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


