/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
)

// checks if the CreateQuarantinePolicyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateQuarantinePolicyRequest{}

// CreateQuarantinePolicyRequest struct for CreateQuarantinePolicyRequest
type CreateQuarantinePolicyRequest struct {
	Data *CreateQuarantinePolicyRequestData `json:"data,omitempty"`
}

// NewCreateQuarantinePolicyRequest instantiates a new CreateQuarantinePolicyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateQuarantinePolicyRequest() *CreateQuarantinePolicyRequest {
	this := CreateQuarantinePolicyRequest{}
	return &this
}

// NewCreateQuarantinePolicyRequestWithDefaults instantiates a new CreateQuarantinePolicyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateQuarantinePolicyRequestWithDefaults() *CreateQuarantinePolicyRequest {
	this := CreateQuarantinePolicyRequest{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateQuarantinePolicyRequest) GetData() CreateQuarantinePolicyRequestData {
	if o == nil || IsNil(o.Data) {
		var ret CreateQuarantinePolicyRequestData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQuarantinePolicyRequest) GetDataOk() (*CreateQuarantinePolicyRequestData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateQuarantinePolicyRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CreateQuarantinePolicyRequestData and assigns it to the Data field.
func (o *CreateQuarantinePolicyRequest) SetData(v CreateQuarantinePolicyRequestData) {
	o.Data = &v
}

func (o CreateQuarantinePolicyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateQuarantinePolicyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateQuarantinePolicyRequest struct {
	value *CreateQuarantinePolicyRequest
	isSet bool
}

func (v NullableCreateQuarantinePolicyRequest) Get() *CreateQuarantinePolicyRequest {
	return v.value
}

func (v *NullableCreateQuarantinePolicyRequest) Set(val *CreateQuarantinePolicyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateQuarantinePolicyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateQuarantinePolicyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateQuarantinePolicyRequest(val *CreateQuarantinePolicyRequest) *NullableCreateQuarantinePolicyRequest {
	return &NullableCreateQuarantinePolicyRequest{value: val, isSet: true}
}

func (v NullableCreateQuarantinePolicyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateQuarantinePolicyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


