/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CreateCloudIamUserRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCloudIamUserRequestData{}

// CreateCloudIamUserRequestData struct for CreateCloudIamUserRequestData
type CreateCloudIamUserRequestData struct {
	Name string `json:"name"`
	Provider string `json:"provider"`
	Email *string `json:"email,omitempty"`
	ArnOrPrincipalId *string `json:"arn_or_principal_id,omitempty"`
	UserType *string `json:"user_type,omitempty"`
	AttachedPolicies map[string]interface{} `json:"attached_policies,omitempty"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	ExternalId *string `json:"external_id,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Credential *CreateAccessReviewRequestDataReviewer `json:"credential,omitempty"`
	Organisation *CreateAccessReviewRequestDataReviewer `json:"organisation,omitempty"`
}

type _CreateCloudIamUserRequestData CreateCloudIamUserRequestData

// NewCreateCloudIamUserRequestData instantiates a new CreateCloudIamUserRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCloudIamUserRequestData(name string, provider string) *CreateCloudIamUserRequestData {
	this := CreateCloudIamUserRequestData{}
	this.Name = name
	this.Provider = provider
	return &this
}

// NewCreateCloudIamUserRequestDataWithDefaults instantiates a new CreateCloudIamUserRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCloudIamUserRequestDataWithDefaults() *CreateCloudIamUserRequestData {
	this := CreateCloudIamUserRequestData{}
	return &this
}

// GetName returns the Name field value
func (o *CreateCloudIamUserRequestData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateCloudIamUserRequestData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateCloudIamUserRequestData) SetName(v string) {
	o.Name = v
}

// GetProvider returns the Provider field value
func (o *CreateCloudIamUserRequestData) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *CreateCloudIamUserRequestData) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *CreateCloudIamUserRequestData) SetProvider(v string) {
	o.Provider = v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CreateCloudIamUserRequestData) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCloudIamUserRequestData) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *CreateCloudIamUserRequestData) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CreateCloudIamUserRequestData) SetEmail(v string) {
	o.Email = &v
}

// GetArnOrPrincipalId returns the ArnOrPrincipalId field value if set, zero value otherwise.
func (o *CreateCloudIamUserRequestData) GetArnOrPrincipalId() string {
	if o == nil || IsNil(o.ArnOrPrincipalId) {
		var ret string
		return ret
	}
	return *o.ArnOrPrincipalId
}

// GetArnOrPrincipalIdOk returns a tuple with the ArnOrPrincipalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCloudIamUserRequestData) GetArnOrPrincipalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ArnOrPrincipalId) {
		return nil, false
	}
	return o.ArnOrPrincipalId, true
}

// HasArnOrPrincipalId returns a boolean if a field has been set.
func (o *CreateCloudIamUserRequestData) HasArnOrPrincipalId() bool {
	if o != nil && !IsNil(o.ArnOrPrincipalId) {
		return true
	}

	return false
}

// SetArnOrPrincipalId gets a reference to the given string and assigns it to the ArnOrPrincipalId field.
func (o *CreateCloudIamUserRequestData) SetArnOrPrincipalId(v string) {
	o.ArnOrPrincipalId = &v
}

// GetUserType returns the UserType field value if set, zero value otherwise.
func (o *CreateCloudIamUserRequestData) GetUserType() string {
	if o == nil || IsNil(o.UserType) {
		var ret string
		return ret
	}
	return *o.UserType
}

// GetUserTypeOk returns a tuple with the UserType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCloudIamUserRequestData) GetUserTypeOk() (*string, bool) {
	if o == nil || IsNil(o.UserType) {
		return nil, false
	}
	return o.UserType, true
}

// HasUserType returns a boolean if a field has been set.
func (o *CreateCloudIamUserRequestData) HasUserType() bool {
	if o != nil && !IsNil(o.UserType) {
		return true
	}

	return false
}

// SetUserType gets a reference to the given string and assigns it to the UserType field.
func (o *CreateCloudIamUserRequestData) SetUserType(v string) {
	o.UserType = &v
}

// GetAttachedPolicies returns the AttachedPolicies field value if set, zero value otherwise.
func (o *CreateCloudIamUserRequestData) GetAttachedPolicies() map[string]interface{} {
	if o == nil || IsNil(o.AttachedPolicies) {
		var ret map[string]interface{}
		return ret
	}
	return o.AttachedPolicies
}

// GetAttachedPoliciesOk returns a tuple with the AttachedPolicies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCloudIamUserRequestData) GetAttachedPoliciesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AttachedPolicies) {
		return map[string]interface{}{}, false
	}
	return o.AttachedPolicies, true
}

// HasAttachedPolicies returns a boolean if a field has been set.
func (o *CreateCloudIamUserRequestData) HasAttachedPolicies() bool {
	if o != nil && !IsNil(o.AttachedPolicies) {
		return true
	}

	return false
}

// SetAttachedPolicies gets a reference to the given map[string]interface{} and assigns it to the AttachedPolicies field.
func (o *CreateCloudIamUserRequestData) SetAttachedPolicies(v map[string]interface{}) {
	o.AttachedPolicies = v
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise.
func (o *CreateCloudIamUserRequestData) GetLastUsedAt() time.Time {
	if o == nil || IsNil(o.LastUsedAt) {
		var ret time.Time
		return ret
	}
	return *o.LastUsedAt
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCloudIamUserRequestData) GetLastUsedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUsedAt) {
		return nil, false
	}
	return o.LastUsedAt, true
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *CreateCloudIamUserRequestData) HasLastUsedAt() bool {
	if o != nil && !IsNil(o.LastUsedAt) {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given time.Time and assigns it to the LastUsedAt field.
func (o *CreateCloudIamUserRequestData) SetLastUsedAt(v time.Time) {
	o.LastUsedAt = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *CreateCloudIamUserRequestData) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCloudIamUserRequestData) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *CreateCloudIamUserRequestData) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *CreateCloudIamUserRequestData) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateCloudIamUserRequestData) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCloudIamUserRequestData) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateCloudIamUserRequestData) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CreateCloudIamUserRequestData) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetCredential returns the Credential field value if set, zero value otherwise.
func (o *CreateCloudIamUserRequestData) GetCredential() CreateAccessReviewRequestDataReviewer {
	if o == nil || IsNil(o.Credential) {
		var ret CreateAccessReviewRequestDataReviewer
		return ret
	}
	return *o.Credential
}

// GetCredentialOk returns a tuple with the Credential field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCloudIamUserRequestData) GetCredentialOk() (*CreateAccessReviewRequestDataReviewer, bool) {
	if o == nil || IsNil(o.Credential) {
		return nil, false
	}
	return o.Credential, true
}

// HasCredential returns a boolean if a field has been set.
func (o *CreateCloudIamUserRequestData) HasCredential() bool {
	if o != nil && !IsNil(o.Credential) {
		return true
	}

	return false
}

// SetCredential gets a reference to the given CreateAccessReviewRequestDataReviewer and assigns it to the Credential field.
func (o *CreateCloudIamUserRequestData) SetCredential(v CreateAccessReviewRequestDataReviewer) {
	o.Credential = &v
}

// GetOrganisation returns the Organisation field value if set, zero value otherwise.
func (o *CreateCloudIamUserRequestData) GetOrganisation() CreateAccessReviewRequestDataReviewer {
	if o == nil || IsNil(o.Organisation) {
		var ret CreateAccessReviewRequestDataReviewer
		return ret
	}
	return *o.Organisation
}

// GetOrganisationOk returns a tuple with the Organisation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCloudIamUserRequestData) GetOrganisationOk() (*CreateAccessReviewRequestDataReviewer, bool) {
	if o == nil || IsNil(o.Organisation) {
		return nil, false
	}
	return o.Organisation, true
}

// HasOrganisation returns a boolean if a field has been set.
func (o *CreateCloudIamUserRequestData) HasOrganisation() bool {
	if o != nil && !IsNil(o.Organisation) {
		return true
	}

	return false
}

// SetOrganisation gets a reference to the given CreateAccessReviewRequestDataReviewer and assigns it to the Organisation field.
func (o *CreateCloudIamUserRequestData) SetOrganisation(v CreateAccessReviewRequestDataReviewer) {
	o.Organisation = &v
}

func (o CreateCloudIamUserRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCloudIamUserRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["provider"] = o.Provider
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.ArnOrPrincipalId) {
		toSerialize["arn_or_principal_id"] = o.ArnOrPrincipalId
	}
	if !IsNil(o.UserType) {
		toSerialize["user_type"] = o.UserType
	}
	if !IsNil(o.AttachedPolicies) {
		toSerialize["attached_policies"] = o.AttachedPolicies
	}
	if !IsNil(o.LastUsedAt) {
		toSerialize["last_used_at"] = o.LastUsedAt
	}
	if !IsNil(o.ExternalId) {
		toSerialize["external_id"] = o.ExternalId
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Credential) {
		toSerialize["credential"] = o.Credential
	}
	if !IsNil(o.Organisation) {
		toSerialize["organisation"] = o.Organisation
	}
	return toSerialize, nil
}

func (o *CreateCloudIamUserRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"provider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCloudIamUserRequestData := _CreateCloudIamUserRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCloudIamUserRequestData)

	if err != nil {
		return err
	}

	*o = CreateCloudIamUserRequestData(varCreateCloudIamUserRequestData)

	return err
}

type NullableCreateCloudIamUserRequestData struct {
	value *CreateCloudIamUserRequestData
	isSet bool
}

func (v NullableCreateCloudIamUserRequestData) Get() *CreateCloudIamUserRequestData {
	return v.value
}

func (v *NullableCreateCloudIamUserRequestData) Set(val *CreateCloudIamUserRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCloudIamUserRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCloudIamUserRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCloudIamUserRequestData(val *CreateCloudIamUserRequestData) *NullableCreateCloudIamUserRequestData {
	return &NullableCreateCloudIamUserRequestData{value: val, isSet: true}
}

func (v NullableCreateCloudIamUserRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCloudIamUserRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


