/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AgentRelease type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentRelease{}

// AgentRelease struct for AgentRelease
type AgentRelease struct {
	Version string `json:"version"`
	BinaryUrl *string `json:"binary_url,omitempty"`
	ChecksumSha256 *string `json:"checksum_sha256,omitempty"`
	ReleaseNotes *string `json:"release_notes,omitempty"`
	RolloutPolicy map[string]interface{} `json:"rollout_policy,omitempty"`
	RolloutPercentage *int32 `json:"rollout_percentage,omitempty"`
	IsStable *bool `json:"is_stable,omitempty"`
	Channel *string `json:"channel,omitempty"`
	MinAgentVersion *string `json:"min_agent_version,omitempty"`
	BinaryUrls map[string]interface{} `json:"binary_urls,omitempty"`
	Architectures map[string]interface{} `json:"architectures,omitempty"`
}

type _AgentRelease AgentRelease

// NewAgentRelease instantiates a new AgentRelease object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentRelease(version string) *AgentRelease {
	this := AgentRelease{}
	this.Version = version
	return &this
}

// NewAgentReleaseWithDefaults instantiates a new AgentRelease object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentReleaseWithDefaults() *AgentRelease {
	this := AgentRelease{}
	return &this
}

// GetVersion returns the Version field value
func (o *AgentRelease) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *AgentRelease) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *AgentRelease) SetVersion(v string) {
	o.Version = v
}

// GetBinaryUrl returns the BinaryUrl field value if set, zero value otherwise.
func (o *AgentRelease) GetBinaryUrl() string {
	if o == nil || IsNil(o.BinaryUrl) {
		var ret string
		return ret
	}
	return *o.BinaryUrl
}

// GetBinaryUrlOk returns a tuple with the BinaryUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRelease) GetBinaryUrlOk() (*string, bool) {
	if o == nil || IsNil(o.BinaryUrl) {
		return nil, false
	}
	return o.BinaryUrl, true
}

// HasBinaryUrl returns a boolean if a field has been set.
func (o *AgentRelease) HasBinaryUrl() bool {
	if o != nil && !IsNil(o.BinaryUrl) {
		return true
	}

	return false
}

// SetBinaryUrl gets a reference to the given string and assigns it to the BinaryUrl field.
func (o *AgentRelease) SetBinaryUrl(v string) {
	o.BinaryUrl = &v
}

// GetChecksumSha256 returns the ChecksumSha256 field value if set, zero value otherwise.
func (o *AgentRelease) GetChecksumSha256() string {
	if o == nil || IsNil(o.ChecksumSha256) {
		var ret string
		return ret
	}
	return *o.ChecksumSha256
}

// GetChecksumSha256Ok returns a tuple with the ChecksumSha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRelease) GetChecksumSha256Ok() (*string, bool) {
	if o == nil || IsNil(o.ChecksumSha256) {
		return nil, false
	}
	return o.ChecksumSha256, true
}

// HasChecksumSha256 returns a boolean if a field has been set.
func (o *AgentRelease) HasChecksumSha256() bool {
	if o != nil && !IsNil(o.ChecksumSha256) {
		return true
	}

	return false
}

// SetChecksumSha256 gets a reference to the given string and assigns it to the ChecksumSha256 field.
func (o *AgentRelease) SetChecksumSha256(v string) {
	o.ChecksumSha256 = &v
}

// GetReleaseNotes returns the ReleaseNotes field value if set, zero value otherwise.
func (o *AgentRelease) GetReleaseNotes() string {
	if o == nil || IsNil(o.ReleaseNotes) {
		var ret string
		return ret
	}
	return *o.ReleaseNotes
}

// GetReleaseNotesOk returns a tuple with the ReleaseNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRelease) GetReleaseNotesOk() (*string, bool) {
	if o == nil || IsNil(o.ReleaseNotes) {
		return nil, false
	}
	return o.ReleaseNotes, true
}

// HasReleaseNotes returns a boolean if a field has been set.
func (o *AgentRelease) HasReleaseNotes() bool {
	if o != nil && !IsNil(o.ReleaseNotes) {
		return true
	}

	return false
}

// SetReleaseNotes gets a reference to the given string and assigns it to the ReleaseNotes field.
func (o *AgentRelease) SetReleaseNotes(v string) {
	o.ReleaseNotes = &v
}

// GetRolloutPolicy returns the RolloutPolicy field value if set, zero value otherwise.
func (o *AgentRelease) GetRolloutPolicy() map[string]interface{} {
	if o == nil || IsNil(o.RolloutPolicy) {
		var ret map[string]interface{}
		return ret
	}
	return o.RolloutPolicy
}

// GetRolloutPolicyOk returns a tuple with the RolloutPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRelease) GetRolloutPolicyOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.RolloutPolicy) {
		return map[string]interface{}{}, false
	}
	return o.RolloutPolicy, true
}

// HasRolloutPolicy returns a boolean if a field has been set.
func (o *AgentRelease) HasRolloutPolicy() bool {
	if o != nil && !IsNil(o.RolloutPolicy) {
		return true
	}

	return false
}

// SetRolloutPolicy gets a reference to the given map[string]interface{} and assigns it to the RolloutPolicy field.
func (o *AgentRelease) SetRolloutPolicy(v map[string]interface{}) {
	o.RolloutPolicy = v
}

// GetRolloutPercentage returns the RolloutPercentage field value if set, zero value otherwise.
func (o *AgentRelease) GetRolloutPercentage() int32 {
	if o == nil || IsNil(o.RolloutPercentage) {
		var ret int32
		return ret
	}
	return *o.RolloutPercentage
}

// GetRolloutPercentageOk returns a tuple with the RolloutPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRelease) GetRolloutPercentageOk() (*int32, bool) {
	if o == nil || IsNil(o.RolloutPercentage) {
		return nil, false
	}
	return o.RolloutPercentage, true
}

// HasRolloutPercentage returns a boolean if a field has been set.
func (o *AgentRelease) HasRolloutPercentage() bool {
	if o != nil && !IsNil(o.RolloutPercentage) {
		return true
	}

	return false
}

// SetRolloutPercentage gets a reference to the given int32 and assigns it to the RolloutPercentage field.
func (o *AgentRelease) SetRolloutPercentage(v int32) {
	o.RolloutPercentage = &v
}

// GetIsStable returns the IsStable field value if set, zero value otherwise.
func (o *AgentRelease) GetIsStable() bool {
	if o == nil || IsNil(o.IsStable) {
		var ret bool
		return ret
	}
	return *o.IsStable
}

// GetIsStableOk returns a tuple with the IsStable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRelease) GetIsStableOk() (*bool, bool) {
	if o == nil || IsNil(o.IsStable) {
		return nil, false
	}
	return o.IsStable, true
}

// HasIsStable returns a boolean if a field has been set.
func (o *AgentRelease) HasIsStable() bool {
	if o != nil && !IsNil(o.IsStable) {
		return true
	}

	return false
}

// SetIsStable gets a reference to the given bool and assigns it to the IsStable field.
func (o *AgentRelease) SetIsStable(v bool) {
	o.IsStable = &v
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *AgentRelease) GetChannel() string {
	if o == nil || IsNil(o.Channel) {
		var ret string
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRelease) GetChannelOk() (*string, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *AgentRelease) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given string and assigns it to the Channel field.
func (o *AgentRelease) SetChannel(v string) {
	o.Channel = &v
}

// GetMinAgentVersion returns the MinAgentVersion field value if set, zero value otherwise.
func (o *AgentRelease) GetMinAgentVersion() string {
	if o == nil || IsNil(o.MinAgentVersion) {
		var ret string
		return ret
	}
	return *o.MinAgentVersion
}

// GetMinAgentVersionOk returns a tuple with the MinAgentVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRelease) GetMinAgentVersionOk() (*string, bool) {
	if o == nil || IsNil(o.MinAgentVersion) {
		return nil, false
	}
	return o.MinAgentVersion, true
}

// HasMinAgentVersion returns a boolean if a field has been set.
func (o *AgentRelease) HasMinAgentVersion() bool {
	if o != nil && !IsNil(o.MinAgentVersion) {
		return true
	}

	return false
}

// SetMinAgentVersion gets a reference to the given string and assigns it to the MinAgentVersion field.
func (o *AgentRelease) SetMinAgentVersion(v string) {
	o.MinAgentVersion = &v
}

// GetBinaryUrls returns the BinaryUrls field value if set, zero value otherwise.
func (o *AgentRelease) GetBinaryUrls() map[string]interface{} {
	if o == nil || IsNil(o.BinaryUrls) {
		var ret map[string]interface{}
		return ret
	}
	return o.BinaryUrls
}

// GetBinaryUrlsOk returns a tuple with the BinaryUrls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRelease) GetBinaryUrlsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.BinaryUrls) {
		return map[string]interface{}{}, false
	}
	return o.BinaryUrls, true
}

// HasBinaryUrls returns a boolean if a field has been set.
func (o *AgentRelease) HasBinaryUrls() bool {
	if o != nil && !IsNil(o.BinaryUrls) {
		return true
	}

	return false
}

// SetBinaryUrls gets a reference to the given map[string]interface{} and assigns it to the BinaryUrls field.
func (o *AgentRelease) SetBinaryUrls(v map[string]interface{}) {
	o.BinaryUrls = v
}

// GetArchitectures returns the Architectures field value if set, zero value otherwise.
func (o *AgentRelease) GetArchitectures() map[string]interface{} {
	if o == nil || IsNil(o.Architectures) {
		var ret map[string]interface{}
		return ret
	}
	return o.Architectures
}

// GetArchitecturesOk returns a tuple with the Architectures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRelease) GetArchitecturesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Architectures) {
		return map[string]interface{}{}, false
	}
	return o.Architectures, true
}

// HasArchitectures returns a boolean if a field has been set.
func (o *AgentRelease) HasArchitectures() bool {
	if o != nil && !IsNil(o.Architectures) {
		return true
	}

	return false
}

// SetArchitectures gets a reference to the given map[string]interface{} and assigns it to the Architectures field.
func (o *AgentRelease) SetArchitectures(v map[string]interface{}) {
	o.Architectures = v
}

func (o AgentRelease) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentRelease) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	if !IsNil(o.BinaryUrl) {
		toSerialize["binary_url"] = o.BinaryUrl
	}
	if !IsNil(o.ChecksumSha256) {
		toSerialize["checksum_sha256"] = o.ChecksumSha256
	}
	if !IsNil(o.ReleaseNotes) {
		toSerialize["release_notes"] = o.ReleaseNotes
	}
	if !IsNil(o.RolloutPolicy) {
		toSerialize["rollout_policy"] = o.RolloutPolicy
	}
	if !IsNil(o.RolloutPercentage) {
		toSerialize["rollout_percentage"] = o.RolloutPercentage
	}
	if !IsNil(o.IsStable) {
		toSerialize["is_stable"] = o.IsStable
	}
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}
	if !IsNil(o.MinAgentVersion) {
		toSerialize["min_agent_version"] = o.MinAgentVersion
	}
	if !IsNil(o.BinaryUrls) {
		toSerialize["binary_urls"] = o.BinaryUrls
	}
	if !IsNil(o.Architectures) {
		toSerialize["architectures"] = o.Architectures
	}
	return toSerialize, nil
}

func (o *AgentRelease) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentRelease := _AgentRelease{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentRelease)

	if err != nil {
		return err
	}

	*o = AgentRelease(varAgentRelease)

	return err
}

type NullableAgentRelease struct {
	value *AgentRelease
	isSet bool
}

func (v NullableAgentRelease) Get() *AgentRelease {
	return v.value
}

func (v *NullableAgentRelease) Set(val *AgentRelease) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentRelease) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentRelease) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentRelease(val *AgentRelease) *NullableAgentRelease {
	return &NullableAgentRelease{value: val, isSet: true}
}

func (v NullableAgentRelease) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentRelease) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


