/*
Sencai Platform API

Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/_*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

API version: 1.0.0
Contact: api@sencai.space
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sencaisdk

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FindOrganisationMember200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindOrganisationMember200ResponseDataInner{}

// FindOrganisationMember200ResponseDataInner struct for FindOrganisationMember200ResponseDataInner
type FindOrganisationMember200ResponseDataInner struct {
	User *CreateAccessReviewRequestDataReviewer `json:"user,omitempty"`
	Organisation CreateAccessReviewRequestDataReviewer `json:"organisation"`
	Role string `json:"role"`
	Email *string `json:"email,omitempty"`
	InvitationToken *string `json:"invitation_token,omitempty"`
	InvitedAt *time.Time `json:"invited_at,omitempty"`
	AcceptedAt *time.Time `json:"accepted_at,omitempty"`
	InvitedBy *CreateAccessReviewRequestDataReviewer `json:"invited_by,omitempty"`
	// Logical data-residency region of the tenant (CELL invariant, F2.CELL.01)
	HomeRegion string `json:"home_region"`
	// Deployment cell within home_region for blast-radius isolation (CELL invariant, F2.CELL.01)
	CellId *string `json:"cell_id,omitempty"`
	DocumentId *string `json:"documentId,omitempty"`
	Id *int32 `json:"id,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	PublishedAt NullableTime `json:"publishedAt,omitempty"`
}

type _FindOrganisationMember200ResponseDataInner FindOrganisationMember200ResponseDataInner

// NewFindOrganisationMember200ResponseDataInner instantiates a new FindOrganisationMember200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindOrganisationMember200ResponseDataInner(organisation CreateAccessReviewRequestDataReviewer, role string, homeRegion string) *FindOrganisationMember200ResponseDataInner {
	this := FindOrganisationMember200ResponseDataInner{}
	this.Organisation = organisation
	this.Role = role
	this.HomeRegion = homeRegion
	return &this
}

// NewFindOrganisationMember200ResponseDataInnerWithDefaults instantiates a new FindOrganisationMember200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindOrganisationMember200ResponseDataInnerWithDefaults() *FindOrganisationMember200ResponseDataInner {
	this := FindOrganisationMember200ResponseDataInner{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *FindOrganisationMember200ResponseDataInner) GetUser() CreateAccessReviewRequestDataReviewer {
	if o == nil || IsNil(o.User) {
		var ret CreateAccessReviewRequestDataReviewer
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindOrganisationMember200ResponseDataInner) GetUserOk() (*CreateAccessReviewRequestDataReviewer, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *FindOrganisationMember200ResponseDataInner) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given CreateAccessReviewRequestDataReviewer and assigns it to the User field.
func (o *FindOrganisationMember200ResponseDataInner) SetUser(v CreateAccessReviewRequestDataReviewer) {
	o.User = &v
}

// GetOrganisation returns the Organisation field value
func (o *FindOrganisationMember200ResponseDataInner) GetOrganisation() CreateAccessReviewRequestDataReviewer {
	if o == nil {
		var ret CreateAccessReviewRequestDataReviewer
		return ret
	}

	return o.Organisation
}

// GetOrganisationOk returns a tuple with the Organisation field value
// and a boolean to check if the value has been set.
func (o *FindOrganisationMember200ResponseDataInner) GetOrganisationOk() (*CreateAccessReviewRequestDataReviewer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organisation, true
}

// SetOrganisation sets field value
func (o *FindOrganisationMember200ResponseDataInner) SetOrganisation(v CreateAccessReviewRequestDataReviewer) {
	o.Organisation = v
}

// GetRole returns the Role field value
func (o *FindOrganisationMember200ResponseDataInner) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *FindOrganisationMember200ResponseDataInner) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *FindOrganisationMember200ResponseDataInner) SetRole(v string) {
	o.Role = v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *FindOrganisationMember200ResponseDataInner) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindOrganisationMember200ResponseDataInner) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *FindOrganisationMember200ResponseDataInner) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *FindOrganisationMember200ResponseDataInner) SetEmail(v string) {
	o.Email = &v
}

// GetInvitationToken returns the InvitationToken field value if set, zero value otherwise.
func (o *FindOrganisationMember200ResponseDataInner) GetInvitationToken() string {
	if o == nil || IsNil(o.InvitationToken) {
		var ret string
		return ret
	}
	return *o.InvitationToken
}

// GetInvitationTokenOk returns a tuple with the InvitationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindOrganisationMember200ResponseDataInner) GetInvitationTokenOk() (*string, bool) {
	if o == nil || IsNil(o.InvitationToken) {
		return nil, false
	}
	return o.InvitationToken, true
}

// HasInvitationToken returns a boolean if a field has been set.
func (o *FindOrganisationMember200ResponseDataInner) HasInvitationToken() bool {
	if o != nil && !IsNil(o.InvitationToken) {
		return true
	}

	return false
}

// SetInvitationToken gets a reference to the given string and assigns it to the InvitationToken field.
func (o *FindOrganisationMember200ResponseDataInner) SetInvitationToken(v string) {
	o.InvitationToken = &v
}

// GetInvitedAt returns the InvitedAt field value if set, zero value otherwise.
func (o *FindOrganisationMember200ResponseDataInner) GetInvitedAt() time.Time {
	if o == nil || IsNil(o.InvitedAt) {
		var ret time.Time
		return ret
	}
	return *o.InvitedAt
}

// GetInvitedAtOk returns a tuple with the InvitedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindOrganisationMember200ResponseDataInner) GetInvitedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.InvitedAt) {
		return nil, false
	}
	return o.InvitedAt, true
}

// HasInvitedAt returns a boolean if a field has been set.
func (o *FindOrganisationMember200ResponseDataInner) HasInvitedAt() bool {
	if o != nil && !IsNil(o.InvitedAt) {
		return true
	}

	return false
}

// SetInvitedAt gets a reference to the given time.Time and assigns it to the InvitedAt field.
func (o *FindOrganisationMember200ResponseDataInner) SetInvitedAt(v time.Time) {
	o.InvitedAt = &v
}

// GetAcceptedAt returns the AcceptedAt field value if set, zero value otherwise.
func (o *FindOrganisationMember200ResponseDataInner) GetAcceptedAt() time.Time {
	if o == nil || IsNil(o.AcceptedAt) {
		var ret time.Time
		return ret
	}
	return *o.AcceptedAt
}

// GetAcceptedAtOk returns a tuple with the AcceptedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindOrganisationMember200ResponseDataInner) GetAcceptedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.AcceptedAt) {
		return nil, false
	}
	return o.AcceptedAt, true
}

// HasAcceptedAt returns a boolean if a field has been set.
func (o *FindOrganisationMember200ResponseDataInner) HasAcceptedAt() bool {
	if o != nil && !IsNil(o.AcceptedAt) {
		return true
	}

	return false
}

// SetAcceptedAt gets a reference to the given time.Time and assigns it to the AcceptedAt field.
func (o *FindOrganisationMember200ResponseDataInner) SetAcceptedAt(v time.Time) {
	o.AcceptedAt = &v
}

// GetInvitedBy returns the InvitedBy field value if set, zero value otherwise.
func (o *FindOrganisationMember200ResponseDataInner) GetInvitedBy() CreateAccessReviewRequestDataReviewer {
	if o == nil || IsNil(o.InvitedBy) {
		var ret CreateAccessReviewRequestDataReviewer
		return ret
	}
	return *o.InvitedBy
}

// GetInvitedByOk returns a tuple with the InvitedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindOrganisationMember200ResponseDataInner) GetInvitedByOk() (*CreateAccessReviewRequestDataReviewer, bool) {
	if o == nil || IsNil(o.InvitedBy) {
		return nil, false
	}
	return o.InvitedBy, true
}

// HasInvitedBy returns a boolean if a field has been set.
func (o *FindOrganisationMember200ResponseDataInner) HasInvitedBy() bool {
	if o != nil && !IsNil(o.InvitedBy) {
		return true
	}

	return false
}

// SetInvitedBy gets a reference to the given CreateAccessReviewRequestDataReviewer and assigns it to the InvitedBy field.
func (o *FindOrganisationMember200ResponseDataInner) SetInvitedBy(v CreateAccessReviewRequestDataReviewer) {
	o.InvitedBy = &v
}

// GetHomeRegion returns the HomeRegion field value
func (o *FindOrganisationMember200ResponseDataInner) GetHomeRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HomeRegion
}

// GetHomeRegionOk returns a tuple with the HomeRegion field value
// and a boolean to check if the value has been set.
func (o *FindOrganisationMember200ResponseDataInner) GetHomeRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HomeRegion, true
}

// SetHomeRegion sets field value
func (o *FindOrganisationMember200ResponseDataInner) SetHomeRegion(v string) {
	o.HomeRegion = v
}

// GetCellId returns the CellId field value if set, zero value otherwise.
func (o *FindOrganisationMember200ResponseDataInner) GetCellId() string {
	if o == nil || IsNil(o.CellId) {
		var ret string
		return ret
	}
	return *o.CellId
}

// GetCellIdOk returns a tuple with the CellId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindOrganisationMember200ResponseDataInner) GetCellIdOk() (*string, bool) {
	if o == nil || IsNil(o.CellId) {
		return nil, false
	}
	return o.CellId, true
}

// HasCellId returns a boolean if a field has been set.
func (o *FindOrganisationMember200ResponseDataInner) HasCellId() bool {
	if o != nil && !IsNil(o.CellId) {
		return true
	}

	return false
}

// SetCellId gets a reference to the given string and assigns it to the CellId field.
func (o *FindOrganisationMember200ResponseDataInner) SetCellId(v string) {
	o.CellId = &v
}

// GetDocumentId returns the DocumentId field value if set, zero value otherwise.
func (o *FindOrganisationMember200ResponseDataInner) GetDocumentId() string {
	if o == nil || IsNil(o.DocumentId) {
		var ret string
		return ret
	}
	return *o.DocumentId
}

// GetDocumentIdOk returns a tuple with the DocumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindOrganisationMember200ResponseDataInner) GetDocumentIdOk() (*string, bool) {
	if o == nil || IsNil(o.DocumentId) {
		return nil, false
	}
	return o.DocumentId, true
}

// HasDocumentId returns a boolean if a field has been set.
func (o *FindOrganisationMember200ResponseDataInner) HasDocumentId() bool {
	if o != nil && !IsNil(o.DocumentId) {
		return true
	}

	return false
}

// SetDocumentId gets a reference to the given string and assigns it to the DocumentId field.
func (o *FindOrganisationMember200ResponseDataInner) SetDocumentId(v string) {
	o.DocumentId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FindOrganisationMember200ResponseDataInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindOrganisationMember200ResponseDataInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FindOrganisationMember200ResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *FindOrganisationMember200ResponseDataInner) SetId(v int32) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *FindOrganisationMember200ResponseDataInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindOrganisationMember200ResponseDataInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *FindOrganisationMember200ResponseDataInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *FindOrganisationMember200ResponseDataInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *FindOrganisationMember200ResponseDataInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindOrganisationMember200ResponseDataInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *FindOrganisationMember200ResponseDataInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *FindOrganisationMember200ResponseDataInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetPublishedAt returns the PublishedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FindOrganisationMember200ResponseDataInner) GetPublishedAt() time.Time {
	if o == nil || IsNil(o.PublishedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.PublishedAt.Get()
}

// GetPublishedAtOk returns a tuple with the PublishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FindOrganisationMember200ResponseDataInner) GetPublishedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PublishedAt.Get(), o.PublishedAt.IsSet()
}

// HasPublishedAt returns a boolean if a field has been set.
func (o *FindOrganisationMember200ResponseDataInner) HasPublishedAt() bool {
	if o != nil && o.PublishedAt.IsSet() {
		return true
	}

	return false
}

// SetPublishedAt gets a reference to the given NullableTime and assigns it to the PublishedAt field.
func (o *FindOrganisationMember200ResponseDataInner) SetPublishedAt(v time.Time) {
	o.PublishedAt.Set(&v)
}
// SetPublishedAtNil sets the value for PublishedAt to be an explicit nil
func (o *FindOrganisationMember200ResponseDataInner) SetPublishedAtNil() {
	o.PublishedAt.Set(nil)
}

// UnsetPublishedAt ensures that no value is present for PublishedAt, not even an explicit nil
func (o *FindOrganisationMember200ResponseDataInner) UnsetPublishedAt() {
	o.PublishedAt.Unset()
}

func (o FindOrganisationMember200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindOrganisationMember200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	toSerialize["organisation"] = o.Organisation
	toSerialize["role"] = o.Role
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.InvitationToken) {
		toSerialize["invitation_token"] = o.InvitationToken
	}
	if !IsNil(o.InvitedAt) {
		toSerialize["invited_at"] = o.InvitedAt
	}
	if !IsNil(o.AcceptedAt) {
		toSerialize["accepted_at"] = o.AcceptedAt
	}
	if !IsNil(o.InvitedBy) {
		toSerialize["invited_by"] = o.InvitedBy
	}
	toSerialize["home_region"] = o.HomeRegion
	if !IsNil(o.CellId) {
		toSerialize["cell_id"] = o.CellId
	}
	if !IsNil(o.DocumentId) {
		toSerialize["documentId"] = o.DocumentId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.PublishedAt.IsSet() {
		toSerialize["publishedAt"] = o.PublishedAt.Get()
	}
	return toSerialize, nil
}

func (o *FindOrganisationMember200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organisation",
		"role",
		"home_region",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFindOrganisationMember200ResponseDataInner := _FindOrganisationMember200ResponseDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFindOrganisationMember200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = FindOrganisationMember200ResponseDataInner(varFindOrganisationMember200ResponseDataInner)

	return err
}

type NullableFindOrganisationMember200ResponseDataInner struct {
	value *FindOrganisationMember200ResponseDataInner
	isSet bool
}

func (v NullableFindOrganisationMember200ResponseDataInner) Get() *FindOrganisationMember200ResponseDataInner {
	return v.value
}

func (v *NullableFindOrganisationMember200ResponseDataInner) Set(val *FindOrganisationMember200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFindOrganisationMember200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFindOrganisationMember200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindOrganisationMember200ResponseDataInner(val *FindOrganisationMember200ResponseDataInner) *NullableFindOrganisationMember200ResponseDataInner {
	return &NullableFindOrganisationMember200ResponseDataInner{value: val, isSet: true}
}

func (v NullableFindOrganisationMember200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindOrganisationMember200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


